-- ============================================================
-- discover-appliances.ts 由来 v2-balanced (カテゴリ別配分)
-- ============================================================
insert into appliances (manufacturer, category, model_number) values
  ('ダイソン', 'vacuum', 'V8 Absolute'),
  ('シャープ', 'vacuum', 'EC-AP500'),
  ('シャープ', 'vacuum', 'EC-AR2S'),
  ('シャープ', 'vacuum', 'EC-AS500'),
  ('シャープ', 'vacuum', 'EC-AS510'),
  ('シャープ', 'vacuum', 'EC-AS710'),
  ('シャープ', 'vacuum', 'EC-SX210'),
  ('シャープ', 'vacuum', 'EC-SX310'),
  ('シャープ', 'vacuum', 'EC-SX320'),
  ('シャープ', 'vacuum', 'EC-SX520'),
  ('シャープ', 'vacuum', 'EC-PR10'),
  ('シャープ', 'vacuum', 'EC-SR11'),
  ('シャープ', 'vacuum', 'EC-AR3S'),
  ('シャープ', 'vacuum', 'EC-FR5'),
  ('シャープ', 'vacuum', 'EC-AH2R'),
  ('シャープ', 'vacuum', 'EC-AH5'),
  ('シャープ', 'vacuum', 'EC-FR10'),
  ('シャープ', 'vacuum', 'EC-KR2'),
  ('シャープ', 'vacuum', 'EC-AR11'),
  ('日立', 'vacuum', 'PV-BL50J'),
  ('日立', 'vacuum', 'PV-BEH800'),
  ('日立', 'vacuum', 'PV-BFH500'),
  ('シャープ', 'vacuum', 'EC-AR7'),
  ('シャープ', 'vacuum', 'EC-SR3S'),
  ('日立', 'vacuum', 'PV-BH500G'),
  ('日立', 'vacuum', 'PV-BH900G'),
  ('日立', 'vacuum', 'PV-BT5000'),
  ('ダイソン', 'vacuum', 'V7 Absolute'),
  ('シャープ', 'vacuum', 'EC-KH9X'),
  ('Panasonic', 'vacuum', 'MC-SB33J'),
  ('シャープ', 'washing_machine', 'ES-GE55R'),
  ('シャープ', 'washing_machine', 'ES-GE6B'),
  ('シャープ', 'washing_machine', 'ES-GE6D'),
  ('シャープ', 'washing_machine', 'ES-PH8C'),
  ('シャープ', 'washing_machine', 'ES-SH7C'),
  ('シャープ', 'washing_machine', 'ES-TX550'),
  ('シャープ', 'washing_machine', 'ES-TX5A'),
  ('シャープ', 'washing_machine', 'ES-TX5B'),
  ('シャープ', 'washing_machine', 'ES-TX5C'),
  ('シャープ', 'washing_machine', 'ES-TX5D'),
  ('シャープ', 'washing_machine', 'ES-TX8E'),
  ('Panasonic', 'washing_machine', 'NA-F60PB10'),
  ('Panasonic', 'washing_machine', 'NA-F60PB11'),
  ('Panasonic', 'washing_machine', 'NA-F60PB13'),
  ('Panasonic', 'washing_machine', 'NA-F70BE5'),
  ('Panasonic', 'washing_machine', 'NA-F70PB13'),
  ('Panasonic', 'washing_machine', 'NA-F7AE3'),
  ('Panasonic', 'washing_machine', 'NA-F7AE4'),
  ('Panasonic', 'washing_machine', 'NA-F7AE5'),
  ('Panasonic', 'washing_machine', 'NA-F7AE6'),
  ('Panasonic', 'washing_machine', 'NA-F8AE3'),
  ('Panasonic', 'washing_machine', 'NA-F8AE4'),
  ('Panasonic', 'washing_machine', 'NA-F8AE5'),
  ('Panasonic', 'washing_machine', 'NA-F8AE6'),
  ('Panasonic', 'washing_machine', 'NA-F9AE3'),
  ('Panasonic', 'washing_machine', 'NA-F9AE4'),
  ('Panasonic', 'washing_machine', 'NA-F9AE5'),
  ('Panasonic', 'washing_machine', 'NA-F9AE6'),
  ('Panasonic', 'washing_machine', 'NA-FA70H5'),
  ('Panasonic', 'washing_machine', 'NA-FA70H6'),
  ('三菱電機', 'refrigerator', 'MR-WX53Y'),
  ('三菱電機', 'refrigerator', 'MR-E57S'),
  ('Panasonic', 'refrigerator', 'NR-F477TM'),
  ('Panasonic', 'refrigerator', 'NR-F518XG'),
  ('三菱電機', 'refrigerator', 'MR-WX47C'),
  ('三菱電機', 'refrigerator', 'MR-WX47D'),
  ('三菱電機', 'refrigerator', 'MR-WX52A'),
  ('三菱電機', 'refrigerator', 'MR-WX52C'),
  ('三菱電機', 'refrigerator', 'MR-WX52D'),
  ('三菱電機', 'refrigerator', 'MR-WX60C'),
  ('三菱電機', 'refrigerator', 'MR-WX60D'),
  ('Panasonic', 'refrigerator', 'NR-F476TM'),
  ('Panasonic', 'refrigerator', 'NR-F556T'),
  ('三菱電機', 'refrigerator', 'MR-WX47A'),
  ('Panasonic', 'refrigerator', 'NR-F606T'),
  ('三菱電機', 'refrigerator', 'MR-MX50E'),
  ('三菱電機', 'refrigerator', 'MR-MX57E'),
  ('Panasonic', 'refrigerator', 'NR-F618XG'),
  ('三菱電機', 'refrigerator', 'MR-E62S'),
  ('三菱電機', 'refrigerator', 'MR-BX53X'),
  ('三菱電機', 'refrigerator', 'MR-R47Z'),
  ('Panasonic', 'refrigerator', 'NR-F505T'),
  ('Panasonic', 'refrigerator', 'NR-F506T'),
  ('Panasonic', 'refrigerator', 'NR-F507T'),
  ('Panasonic', 'refrigerator', 'NR-F557T'),
  ('日立', 'refrigerator', 'R-B6200'),
  ('三菱電機', 'refrigerator', 'MR-MX46E'),
  ('日立', 'refrigerator', 'R-B5200'),
  ('日立', 'refrigerator', 'R-B5700'),
  ('日立', 'refrigerator', 'R-C6700'),
  ('Panasonic', 'air_conditioner', 'CS-XS229C'),
  ('Panasonic', 'air_conditioner', 'CS-XS289C2'),
  ('Panasonic', 'air_conditioner', 'CS-XS369C2'),
  ('Panasonic', 'air_conditioner', 'CS-XS289C'),
  ('Panasonic', 'air_conditioner', 'CS-XS409C'),
  ('Panasonic', 'air_conditioner', 'CS-XS719C2'),
  ('日立', 'air_conditioner', 'RAS-A22Z'),
  ('日立', 'air_conditioner', 'RAS-VL7125D'),
  ('日立', 'air_conditioner', 'RAS-VJ2226S'),
  ('Panasonic', 'air_conditioner', 'CS-XS569C2'),
  ('Panasonic', 'air_conditioner', 'CS-XS409C2'),
  ('Panasonic', 'air_conditioner', 'CS-XS809C2'),
  ('日立', 'air_conditioner', 'RAS-N28V'),
  ('日立', 'air_conditioner', 'RAS-MJ4026D'),
  ('Panasonic', 'air_conditioner', 'CS-X228C'),
  ('Panasonic', 'air_conditioner', 'CS-X228CZ'),
  ('Panasonic', 'air_conditioner', 'CS-X258C'),
  ('Panasonic', 'air_conditioner', 'CS-X258CZ'),
  ('Panasonic', 'air_conditioner', 'CS-X259C'),
  ('Panasonic', 'air_conditioner', 'CS-X288C'),
  ('Panasonic', 'air_conditioner', 'CS-XS259C'),
  ('Panasonic', 'air_conditioner', 'CS-XS369C'),
  ('Panasonic', 'air_conditioner', 'CS-XS909C2'),
  ('Panasonic', 'air_conditioner', 'CS-XS639C2'),
  ('三菱電機', 'air_conditioner', 'MSZ-HXV2518'),
  ('三菱電機', 'air_conditioner', 'MSZ-HXV2818S'),
  ('三菱電機', 'air_conditioner', 'MSZ-HXV4018S'),
  ('三菱電機', 'air_conditioner', 'MSZ-HXV5618S'),
  ('三菱電機', 'air_conditioner', 'MSZ-HXV6318S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW222'),
  ('Panasonic', 'air_conditioner', 'CS-X369C'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW252'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW282S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW282'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW362S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW362'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW402S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW562S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW632S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW712S'),
  ('象印', 'rice_cooker', 'NW-SB10'),
  ('Panasonic', 'rice_cooker', 'SR-PGA54'),
  ('Panasonic', 'rice_cooker', 'SR-PGB54'),
  ('日立', 'rice_cooker', 'RZ-YW3000M'),
  ('Panasonic', 'rice_cooker', 'SR-HX108'),
  ('Panasonic', 'rice_cooker', 'SR-HX109'),
  ('Panasonic', 'rice_cooker', 'SR-HX100'),
  ('Panasonic', 'rice_cooker', 'SR-SPX107'),
  ('Panasonic', 'rice_cooker', 'SR-SY105J'),
  ('Panasonic', 'rice_cooker', 'SR-SY106J'),
  ('Panasonic', 'rice_cooker', 'SR-CVSX180'),
  ('東芝', 'rice_cooker', 'RC-10VSN'),
  ('日立', 'rice_cooker', 'RZ-YV100M'),
  ('Panasonic', 'rice_cooker', 'SR-PGC54'),
  ('象印', 'rice_cooker', 'NW-NB10'),
  ('Panasonic', 'rice_cooker', 'SR-HX107'),
  ('Panasonic', 'rice_cooker', 'SR-HB109'),
  ('Panasonic', 'rice_cooker', 'SR-HB107'),
  ('Panasonic', 'rice_cooker', 'SR-HB104'),
  ('Panasonic', 'rice_cooker', 'SR-SPX187'),
  ('象印', 'rice_cooker', 'NW-QA10'),
  ('象印', 'rice_cooker', 'NW-UT07'),
  ('東芝', 'rice_cooker', 'RC-10VRL'),
  ('東芝', 'rice_cooker', 'RC-10VRM'),
  ('東芝', 'rice_cooker', 'RC-10VRN'),
  ('東芝', 'rice_cooker', 'RC-10VSL'),
  ('東芝', 'rice_cooker', 'RC-10VSM'),
  ('東芝', 'rice_cooker', 'RC-10VXN'),
  ('Panasonic', 'rice_cooker', 'SR-PB106'),
  ('Panasonic', 'rice_cooker', 'SR-PB107'),
  ('Panasonic', 'rice_cooker', 'SR-PB108'),
  ('Panasonic', 'rice_cooker', 'SR-PB109'),
  ('Panasonic', 'rice_cooker', 'SR-HB108'),
  ('Panasonic', 'rice_cooker', 'SR-HB100'),
  ('象印', 'rice_cooker', 'NW-NB18'),
  ('タイガー魔法瓶', 'rice_cooker', 'JPB-R100W'),
  ('東芝', 'rice_cooker', 'RC-188VSS'),
  ('東芝', 'rice_cooker', 'RC-189VSS'),
  ('東芝', 'rice_cooker', 'RC-18VRL'),
  ('東芝', 'rice_cooker', 'RC-18VRM'),
  ('東芝', 'rice_cooker', 'RC-18VRN'),
  ('東芝', 'rice_cooker', 'RC-18VSL'),
  ('東芝', 'rice_cooker', 'RC-18VSM'),
  ('東芝', 'rice_cooker', 'RC-18VSN'),
  ('東芝', 'rice_cooker', 'RC-10VXM'),
  ('三菱電機', 'rice_cooker', 'NJ-BW10G'),
  ('三菱電機', 'rice_cooker', 'NJ-SV06R'),
  ('三菱電機', 'rice_cooker', 'NJ-VS10G'),
  ('Panasonic', 'rice_cooker', 'SR-PGB54P'),
  ('Panasonic', 'rice_cooker', 'SR-PGB54A'),
  ('Panasonic', 'rice_cooker', 'SR-PGA54A'),
  ('Panasonic', 'rice_cooker', 'SR-MPB100'),
  ('Panasonic', 'rice_cooker', 'SR-SPX186'),
  ('象印', 'rice_cooker', 'NW-CA10'),
  ('三菱電機', 'rice_cooker', 'NJ-AW108'),
  ('三菱電機', 'rice_cooker', 'NJ-SE06H'),
  ('日立', 'rice_cooker', 'RZ-WW3000M'),
  ('Panasonic', 'rice_cooker', 'SR-PW106'),
  ('Panasonic', 'rice_cooker', 'SR-PW107'),
  ('Panasonic', 'rice_cooker', 'SR-SPA106'),
  ('シャープ', 'microwave', 'AX-HC2'),
  ('東芝', 'microwave', 'ER-ND8'),
  ('東芝', 'microwave', 'ER-PD8'),
  ('日立', 'microwave', 'MRO-BK1000'),
  ('日立', 'microwave', 'MRO-GV200'),
  ('東芝', 'microwave', 'ER-G3'),
  ('Panasonic', 'microwave', 'NE-S410F'),
  ('日立', 'microwave', 'MRO-FA4'),
  ('日立', 'microwave', 'MRO-NBK5000'),
  ('東芝', 'microwave', 'ER-JD8'),
  ('東芝', 'microwave', 'ER-JD8A'),
  ('東芝', 'microwave', 'ER-LD8'),
  ('東芝', 'microwave', 'ER-KD8'),
  ('東芝', 'microwave', 'ER-MD8'),
  ('東芝', 'microwave', 'ER-RD8'),
  ('東芝', 'microwave', 'ER-RD8E'),
  ('東芝', 'microwave', 'ER-SD80'),
  ('東芝', 'microwave', 'ER-SD80E'),
  ('Panasonic', 'microwave', 'NE-EH224'),
  ('Panasonic', 'microwave', 'NE-BS657'),
  ('日立', 'microwave', 'MRO-FV100'),
  ('日立', 'microwave', 'MRO-MBK5000'),
  ('日立', 'microwave', 'MRO-MBK3000'),
  ('日立', 'microwave', 'MRO-LV100'),
  ('東芝', 'microwave', 'ER-JD7'),
  ('東芝', 'microwave', 'ER-JD7A'),
  ('東芝', 'microwave', 'ER-LD7'),
  ('東芝', 'microwave', 'ER-KD7'),
  ('東芝', 'microwave', 'ER-M6'),
  ('東芝', 'microwave', 'ER-MD7')
on conflict (manufacturer, model_number) do nothing;

insert into parts (name, category, kind, manufacturer) values
  ('バッテリー V8 Absolute', 'battery', 'oem', 'ダイソン'),
  ('バッテリー EC-AP500', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-AR2S', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-AS500', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-AS510', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-AS710', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-SX210', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-SX310', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-SX320', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-SX520', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-PR10', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-SR11', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-AR3S', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-FR5', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-AH2R', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-AH5', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-FR10', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-KR2', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-AR11', 'battery', 'oem', 'シャープ'),
  ('バッテリー PV-BL50J', 'battery', 'oem', '日立'),
  ('バッテリー PV-BEH800', 'battery', 'oem', '日立'),
  ('バッテリー PV-BFH500', 'battery', 'oem', '日立'),
  ('バッテリー EC-AR7', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-SR3S', 'battery', 'oem', 'シャープ'),
  ('バッテリー PV-BH500G', 'battery', 'oem', '日立'),
  ('バッテリー PV-BH900G', 'battery', 'oem', '日立'),
  ('バッテリー PV-BT5000', 'battery', 'oem', '日立'),
  ('バッテリー V7 Absolute', 'battery', 'oem', 'ダイソン'),
  ('バッテリー EC-KH9X', 'battery', 'oem', 'シャープ'),
  ('バッテリー MC-SB33J', 'battery', 'oem', 'Panasonic'),
  ('糸くずフィルター ES-GE55R', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GE6B', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GE6D', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-PH8C', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-SH7C', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TX550', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TX5A', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TX5B', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TX5C', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TX5D', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TX8E', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター NA-F60PB10', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-F60PB11', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-F60PB13', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-F70BE5', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-F70PB13', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-F7AE3', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-F7AE4', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-F7AE5', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-F7AE6', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-F8AE3', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-F8AE4', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-F8AE5', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-F8AE6', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-F9AE3', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-F9AE4', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-F9AE5', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-F9AE6', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA70H5', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA70H6', 'filter', 'oem', 'Panasonic'),
  ('製氷皿 MR-WX53Y', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-E57S', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 NR-F477TM', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F518XG', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 MR-WX47C', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-WX47D', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-WX52A', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-WX52C', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-WX52D', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-WX60C', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-WX60D', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 NR-F476TM', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F556T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 MR-WX47A', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 NR-F606T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 MR-MX50E', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-MX57E', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 NR-F618XG', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 MR-E62S', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-BX53X', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-R47Z', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 NR-F505T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F506T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F507T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F557T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 R-B6200', 'ice_tray', 'oem', '日立'),
  ('製氷皿 MR-MX46E', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 R-B5200', 'ice_tray', 'oem', '日立'),
  ('製氷皿 R-B5700', 'ice_tray', 'oem', '日立'),
  ('製氷皿 R-C6700', 'ice_tray', 'oem', '日立'),
  ('フィルター CS-XS229C', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS289C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS369C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS289C', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS409C', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS719C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター RAS-A22Z', 'filter', 'oem', '日立'),
  ('フィルター RAS-VL7125D', 'filter', 'oem', '日立'),
  ('フィルター RAS-VJ2226S', 'filter', 'oem', '日立'),
  ('フィルター CS-XS569C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS409C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS809C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター RAS-N28V', 'filter', 'oem', '日立'),
  ('フィルター RAS-MJ4026D', 'filter', 'oem', '日立'),
  ('フィルター CS-X228C', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X228CZ', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X258C', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X258CZ', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X259C', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X288C', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS259C', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS369C', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS909C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS639C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター MSZ-HXV2518', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-HXV2818S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-HXV4018S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-HXV5618S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-HXV6318S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW222', 'filter', 'oem', '三菱電機'),
  ('フィルター CS-X369C', 'filter', 'oem', 'Panasonic'),
  ('フィルター MSZ-ZW252', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW282S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW282', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW362S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW362', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW402S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW562S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW632S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW712S', 'filter', 'oem', '三菱電機'),
  ('内釜 NW-SB10', 'inner_pot', 'oem', '象印'),
  ('内釜 SR-PGA54', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-PGB54', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 RZ-YW3000M', 'inner_pot', 'oem', '日立'),
  ('内釜 SR-HX108', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-HX109', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-HX100', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-SPX107', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-SY105J', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-SY106J', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-CVSX180', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 RC-10VSN', 'inner_pot', 'oem', '東芝'),
  ('内釜 RZ-YV100M', 'inner_pot', 'oem', '日立'),
  ('内釜 SR-PGC54', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 NW-NB10', 'inner_pot', 'oem', '象印'),
  ('内釜 SR-HX107', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-HB109', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-HB107', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-HB104', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-SPX187', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 NW-QA10', 'inner_pot', 'oem', '象印'),
  ('内釜 NW-UT07', 'inner_pot', 'oem', '象印'),
  ('内釜 RC-10VRL', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-10VRM', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-10VRN', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-10VSL', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-10VSM', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-10VXN', 'inner_pot', 'oem', '東芝'),
  ('内釜 SR-PB106', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-PB107', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-PB108', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-PB109', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-HB108', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-HB100', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 NW-NB18', 'inner_pot', 'oem', '象印'),
  ('内釜 JPB-R100W', 'inner_pot', 'oem', 'タイガー魔法瓶'),
  ('内釜 RC-188VSS', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-189VSS', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-18VRL', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-18VRM', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-18VRN', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-18VSL', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-18VSM', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-18VSN', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-10VXM', 'inner_pot', 'oem', '東芝'),
  ('内釜 NJ-BW10G', 'inner_pot', 'oem', '三菱電機'),
  ('内釜 NJ-SV06R', 'inner_pot', 'oem', '三菱電機'),
  ('内釜 NJ-VS10G', 'inner_pot', 'oem', '三菱電機'),
  ('内釜 SR-PGB54P', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-PGB54A', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-PGA54A', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-MPB100', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-SPX186', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 NW-CA10', 'inner_pot', 'oem', '象印'),
  ('内釜 NJ-AW108', 'inner_pot', 'oem', '三菱電機'),
  ('内釜 NJ-SE06H', 'inner_pot', 'oem', '三菱電機'),
  ('内釜 RZ-WW3000M', 'inner_pot', 'oem', '日立'),
  ('内釜 SR-PW106', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-PW107', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-SPA106', 'inner_pot', 'oem', 'Panasonic'),
  ('ターンテーブル AX-HC2', 'turntable', 'oem', 'シャープ'),
  ('ターンテーブル ER-ND8', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-PD8', 'turntable', 'oem', '東芝'),
  ('ターンテーブル MRO-BK1000', 'turntable', 'oem', '日立'),
  ('ターンテーブル MRO-GV200', 'turntable', 'oem', '日立'),
  ('ターンテーブル ER-G3', 'turntable', 'oem', '東芝'),
  ('ターンテーブル NE-S410F', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル MRO-FA4', 'turntable', 'oem', '日立'),
  ('ターンテーブル MRO-NBK5000', 'turntable', 'oem', '日立'),
  ('ターンテーブル ER-JD8', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-JD8A', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-LD8', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-KD8', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-MD8', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-RD8', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-RD8E', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-SD80', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-SD80E', 'turntable', 'oem', '東芝'),
  ('ターンテーブル NE-EH224', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-BS657', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル MRO-FV100', 'turntable', 'oem', '日立'),
  ('ターンテーブル MRO-MBK5000', 'turntable', 'oem', '日立'),
  ('ターンテーブル MRO-MBK3000', 'turntable', 'oem', '日立'),
  ('ターンテーブル MRO-LV100', 'turntable', 'oem', '日立'),
  ('ターンテーブル ER-JD7', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-JD7A', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-LD7', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-KD7', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-M6', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-MD7', 'turntable', 'oem', '東芝')
on conflict do nothing;

insert into appliance_parts (appliance_id, part_id, fitment_note)
select a.id, p.id, null
from parts p
join appliances a on p.name like '%' || a.model_number
where a.model_number in ('V8 Absolute', 'EC-AP500', 'EC-AR2S', 'EC-AS500', 'EC-AS510', 'EC-AS710', 'EC-SX210', 'EC-SX310', 'EC-SX320', 'EC-SX520', 'EC-PR10', 'EC-SR11', 'EC-AR3S', 'EC-FR5', 'EC-AH2R', 'EC-AH5', 'EC-FR10', 'EC-KR2', 'EC-AR11', 'PV-BL50J', 'PV-BEH800', 'PV-BFH500', 'EC-AR7', 'EC-SR3S', 'PV-BH500G', 'PV-BH900G', 'PV-BT5000', 'V7 Absolute', 'EC-KH9X', 'MC-SB33J', 'ES-GE55R', 'ES-GE6B', 'ES-GE6D', 'ES-PH8C', 'ES-SH7C', 'ES-TX550', 'ES-TX5A', 'ES-TX5B', 'ES-TX5C', 'ES-TX5D', 'ES-TX8E', 'NA-F60PB10', 'NA-F60PB11', 'NA-F60PB13', 'NA-F70BE5', 'NA-F70PB13', 'NA-F7AE3', 'NA-F7AE4', 'NA-F7AE5', 'NA-F7AE6', 'NA-F8AE3', 'NA-F8AE4', 'NA-F8AE5', 'NA-F8AE6', 'NA-F9AE3', 'NA-F9AE4', 'NA-F9AE5', 'NA-F9AE6', 'NA-FA70H5', 'NA-FA70H6', 'MR-WX53Y', 'MR-E57S', 'NR-F477TM', 'NR-F518XG', 'MR-WX47C', 'MR-WX47D', 'MR-WX52A', 'MR-WX52C', 'MR-WX52D', 'MR-WX60C', 'MR-WX60D', 'NR-F476TM', 'NR-F556T', 'MR-WX47A', 'NR-F606T', 'MR-MX50E', 'MR-MX57E', 'NR-F618XG', 'MR-E62S', 'MR-BX53X', 'MR-R47Z', 'NR-F505T', 'NR-F506T', 'NR-F507T', 'NR-F557T', 'R-B6200', 'MR-MX46E', 'R-B5200', 'R-B5700', 'R-C6700', 'CS-XS229C', 'CS-XS289C2', 'CS-XS369C2', 'CS-XS289C', 'CS-XS409C', 'CS-XS719C2', 'RAS-A22Z', 'RAS-VL7125D', 'RAS-VJ2226S', 'CS-XS569C2', 'CS-XS409C2', 'CS-XS809C2', 'RAS-N28V', 'RAS-MJ4026D', 'CS-X228C', 'CS-X228CZ', 'CS-X258C', 'CS-X258CZ', 'CS-X259C', 'CS-X288C', 'CS-XS259C', 'CS-XS369C', 'CS-XS909C2', 'CS-XS639C2', 'MSZ-HXV2518', 'MSZ-HXV2818S', 'MSZ-HXV4018S', 'MSZ-HXV5618S', 'MSZ-HXV6318S', 'MSZ-ZW222', 'CS-X369C', 'MSZ-ZW252', 'MSZ-ZW282S', 'MSZ-ZW282', 'MSZ-ZW362S', 'MSZ-ZW362', 'MSZ-ZW402S', 'MSZ-ZW562S', 'MSZ-ZW632S', 'MSZ-ZW712S', 'NW-SB10', 'SR-PGA54', 'SR-PGB54', 'RZ-YW3000M', 'SR-HX108', 'SR-HX109', 'SR-HX100', 'SR-SPX107', 'SR-SY105J', 'SR-SY106J', 'SR-CVSX180', 'RC-10VSN', 'RZ-YV100M', 'SR-PGC54', 'NW-NB10', 'SR-HX107', 'SR-HB109', 'SR-HB107', 'SR-HB104', 'SR-SPX187', 'NW-QA10', 'NW-UT07', 'RC-10VRL', 'RC-10VRM', 'RC-10VRN', 'RC-10VSL', 'RC-10VSM', 'RC-10VXN', 'SR-PB106', 'SR-PB107', 'SR-PB108', 'SR-PB109', 'SR-HB108', 'SR-HB100', 'NW-NB18', 'JPB-R100W', 'RC-188VSS', 'RC-189VSS', 'RC-18VRL', 'RC-18VRM', 'RC-18VRN', 'RC-18VSL', 'RC-18VSM', 'RC-18VSN', 'RC-10VXM', 'NJ-BW10G', 'NJ-SV06R', 'NJ-VS10G', 'SR-PGB54P', 'SR-PGB54A', 'SR-PGA54A', 'SR-MPB100', 'SR-SPX186', 'NW-CA10', 'NJ-AW108', 'NJ-SE06H', 'RZ-WW3000M', 'SR-PW106', 'SR-PW107', 'SR-SPA106', 'AX-HC2', 'ER-ND8', 'ER-PD8', 'MRO-BK1000', 'MRO-GV200', 'ER-G3', 'NE-S410F', 'MRO-FA4', 'MRO-NBK5000', 'ER-JD8', 'ER-JD8A', 'ER-LD8', 'ER-KD8', 'ER-MD8', 'ER-RD8', 'ER-RD8E', 'ER-SD80', 'ER-SD80E', 'NE-EH224', 'NE-BS657', 'MRO-FV100', 'MRO-MBK5000', 'MRO-MBK3000', 'MRO-LV100', 'ER-JD7', 'ER-JD7A', 'ER-LD7', 'ER-KD7', 'ER-M6', 'ER-MD7')
and not exists (
  select 1 from appliance_parts ap where ap.appliance_id = a.id and ap.part_id = p.id
);
