-- ============================================================
-- discover-appliances.ts 由来 v3 (max expansion)
-- occurrences >= 4 のすべての実モデルをカテゴリ別配分で投入
-- ============================================================
insert into appliances (manufacturer, category, model_number) values
  ('シャープ', 'washing_machine', 'ES-LP2'),
  ('シャープ', 'washing_machine', 'ES-LP1'),
  ('シャープ', 'washing_machine', 'ES-PX8C'),
  ('シャープ', 'washing_machine', 'ES-PX8D'),
  ('シャープ', 'washing_machine', 'ES-TX840'),
  ('シャープ', 'washing_machine', 'ES-GX850'),
  ('シャープ', 'washing_machine', 'ES-GX8A'),
  ('シャープ', 'washing_machine', 'ES-PX8B'),
  ('シャープ', 'washing_machine', 'ES-TX830'),
  ('Panasonic', 'washing_machine', 'NA-FA120V1'),
  ('Panasonic', 'washing_machine', 'NA-FA70H2'),
  ('Panasonic', 'washing_machine', 'NA-FA70H3'),
  ('Panasonic', 'washing_machine', 'NA-FA80H2'),
  ('Panasonic', 'washing_machine', 'NA-FA80H3'),
  ('Panasonic', 'washing_machine', 'NA-FA80H5'),
  ('Panasonic', 'washing_machine', 'NA-FA80H6'),
  ('Panasonic', 'washing_machine', 'NA-FA90H6'),
  ('Panasonic', 'washing_machine', 'NA-FA90H5'),
  ('Panasonic', 'washing_machine', 'NA-FA100H7'),
  ('Panasonic', 'washing_machine', 'NA-FA80H7'),
  ('Panasonic', 'washing_machine', 'NA-FA90H7'),
  ('Panasonic', 'washing_machine', 'NA-FA120V2'),
  ('Panasonic', 'washing_machine', 'NA-FA100H9'),
  ('Panasonic', 'washing_machine', 'NA-FA10K1'),
  ('Panasonic', 'washing_machine', 'NA-FA80H9'),
  ('Panasonic', 'washing_machine', 'NA-FA90H9'),
  ('Panasonic', 'washing_machine', 'NA-FA100H8'),
  ('Panasonic', 'washing_machine', 'NA-FA80H8'),
  ('Panasonic', 'washing_machine', 'NA-FW100K9'),
  ('シャープ', 'washing_machine', 'ES-GE7A'),
  ('シャープ', 'washing_machine', 'ES-TX74'),
  ('日立', 'washing_machine', 'BW-D10WV'),
  ('日立', 'washing_machine', 'BW-D10XTV'),
  ('シャープ', 'washing_machine', 'ES-GE60P'),
  ('シャープ', 'washing_machine', 'ES-GE70R'),
  ('シャープ', 'washing_machine', 'ES-GE7B'),
  ('シャープ', 'washing_machine', 'ES-GE7C'),
  ('シャープ', 'washing_machine', 'ES-GE7D'),
  ('シャープ', 'washing_machine', 'ES-PW10D'),
  ('Panasonic', 'washing_machine', 'NA-FW100K8'),
  ('Panasonic', 'washing_machine', 'NA-FA120V3'),
  ('Panasonic', 'washing_machine', 'NA-FA90H8'),
  ('シャープ', 'washing_machine', 'ES-GE60N'),
  ('シャープ', 'washing_machine', 'ES-GV8A'),
  ('シャープ', 'washing_machine', 'ES-GV9B'),
  ('シャープ', 'washing_machine', 'ES-GV9C'),
  ('シャープ', 'washing_machine', 'ES-KSV9C'),
  ('シャープ', 'washing_machine', 'ES-PT10C'),
  ('シャープ', 'washing_machine', 'ES-PT10D'),
  ('シャープ', 'washing_machine', 'ES-PU10C'),
  ('シャープ', 'washing_machine', 'ES-PU11B'),
  ('シャープ', 'washing_machine', 'ES-PU11C'),
  ('シャープ', 'washing_machine', 'ES-PW11D'),
  ('シャープ', 'washing_machine', 'ES-PW8D'),
  ('シャープ', 'washing_machine', 'ES-PX10A'),
  ('シャープ', 'washing_machine', 'ES-PX10B'),
  ('シャープ', 'washing_machine', 'ES-PX9B'),
  ('シャープ', 'washing_machine', 'ES-T707'),
  ('シャープ', 'washing_machine', 'ES-T708'),
  ('シャープ', 'washing_machine', 'ES-T711'),
  ('シャープ', 'washing_machine', 'ES-TX8A'),
  ('シャープ', 'washing_machine', 'ES-TX8B'),
  ('シャープ', 'washing_machine', 'ES-TX8C'),
  ('シャープ', 'washing_machine', 'ES-TX930'),
  ('シャープ', 'washing_machine', 'ES-TX940'),
  ('シャープ', 'washing_machine', 'ES-TX9A'),
  ('Panasonic', 'washing_machine', 'NA-F70PB15'),
  ('シャープ', 'washing_machine', 'ES-GE70N'),
  ('シャープ', 'washing_machine', 'ES-GE70P'),
  ('シャープ', 'washing_machine', 'ES-GV10B'),
  ('シャープ', 'washing_machine', 'ES-GV10C'),
  ('シャープ', 'washing_machine', 'ES-GV10D'),
  ('シャープ', 'washing_machine', 'ES-GV80R'),
  ('シャープ', 'washing_machine', 'ES-GV8B'),
  ('シャープ', 'washing_machine', 'ES-GV8C'),
  ('シャープ', 'washing_machine', 'ES-GV8D'),
  ('シャープ', 'washing_machine', 'ES-GV90R'),
  ('シャープ', 'washing_machine', 'ES-GV9A'),
  ('シャープ', 'washing_machine', 'ES-GV9D'),
  ('シャープ', 'washing_machine', 'ES-GW11D'),
  ('シャープ', 'washing_machine', 'ES-GX950'),
  ('シャープ', 'washing_machine', 'ES-GX9A'),
  ('シャープ', 'washing_machine', 'ES-KS70P'),
  ('シャープ', 'washing_machine', 'ES-KS70R'),
  ('シャープ', 'washing_machine', 'ES-KS70S'),
  ('シャープ', 'washing_machine', 'ES-KS70U'),
  ('シャープ', 'washing_machine', 'ES-T706'),
  ('シャープ', 'washing_machine', 'ES-TX8D'),
  ('シャープ', 'washing_machine', 'ES-GE55N'),
  ('シャープ', 'washing_machine', 'ES-KS70N'),
  ('シャープ', 'washing_machine', 'ES-KSV9B'),
  ('シャープ', 'washing_machine', 'ES-KSV9D'),
  ('シャープ', 'washing_machine', 'ES-T709'),
  ('シャープ', 'washing_machine', 'ES-T710'),
  ('シャープ', 'washing_machine', 'ES-TA840'),
  ('シャープ', 'washing_machine', 'ES-TX750'),
  ('シャープ', 'washing_machine', 'ES-TX850'),
  ('シャープ', 'washing_machine', 'ES-TX950'),
  ('シャープ', 'washing_machine', 'ES-TG74V'),
  ('Panasonic', 'washing_machine', 'NA-F60PB12'),
  ('三菱電機', 'refrigerator', 'MR-WX53Z'),
  ('三菱電機', 'refrigerator', 'MR-JX53Z'),
  ('三菱電機', 'refrigerator', 'MR-WX48Z'),
  ('三菱電機', 'refrigerator', 'MR-WX61Z'),
  ('三菱電機', 'refrigerator', 'MR-B46Z'),
  ('三菱電機', 'refrigerator', 'MR-JX61Z'),
  ('三菱電機', 'refrigerator', 'MR-WX70C'),
  ('三菱電機', 'refrigerator', 'MR-WX71Z'),
  ('三菱電機', 'refrigerator', 'MR-JX53X'),
  ('三菱電機', 'refrigerator', 'MR-JX52W'),
  ('三菱電機', 'refrigerator', 'MR-JX53Y'),
  ('東芝', 'refrigerator', 'GR-M15BS'),
  ('Panasonic', 'refrigerator', 'NR-F561XPV'),
  ('三菱電機', 'refrigerator', 'MR-JX60W'),
  ('三菱電機', 'refrigerator', 'MR-B46D'),
  ('三菱電機', 'refrigerator', 'MR-MB45E'),
  ('三菱電機', 'refrigerator', 'MR-MX57D'),
  ('三菱電機', 'refrigerator', 'MR-RX46A'),
  ('三菱電機', 'refrigerator', 'MR-WX61Y'),
  ('三菱電機', 'refrigerator', 'MR-WX71Y'),
  ('Panasonic', 'refrigerator', 'NR-E438T'),
  ('Panasonic', 'refrigerator', 'NR-F605T'),
  ('日立', 'refrigerator', 'R-B6700'),
  ('三菱電機', 'refrigerator', 'MR-JX64W'),
  ('三菱電機', 'refrigerator', 'MR-JX52A'),
  ('三菱電機', 'refrigerator', 'MR-JX60A'),
  ('三菱電機', 'refrigerator', 'MR-MX50D'),
  ('三菱電機', 'refrigerator', 'MR-JX61X'),
  ('三菱電機', 'refrigerator', 'MR-JX61Y'),
  ('東芝', 'refrigerator', 'GR-M17BS'),
  ('東芝', 'refrigerator', 'GR-P15BS'),
  ('東芝', 'refrigerator', 'GR-P17BS'),
  ('東芝', 'refrigerator', 'GR-R15BS'),
  ('東芝', 'refrigerator', 'GR-R17BS'),
  ('東芝', 'refrigerator', 'GR-S15BS'),
  ('東芝', 'refrigerator', 'GR-S17BS'),
  ('東芝', 'refrigerator', 'GR-T15BS'),
  ('東芝', 'refrigerator', 'GR-T17BS'),
  ('東芝', 'refrigerator', 'GR-U15BS'),
  ('東芝', 'refrigerator', 'GR-U17BS'),
  ('東芝', 'refrigerator', 'GR-V15BS'),
  ('東芝', 'refrigerator', 'GR-V17BS'),
  ('Panasonic', 'refrigerator', 'NR-E434T'),
  ('Panasonic', 'refrigerator', 'NR-F506XV'),
  ('東芝', 'refrigerator', 'GR-G51FXV'),
  ('東芝', 'refrigerator', 'GR-P510FD'),
  ('Panasonic', 'refrigerator', 'NR-E434TL'),
  ('Panasonic', 'refrigerator', 'NR-E435T'),
  ('Panasonic', 'refrigerator', 'NR-E435TL'),
  ('Panasonic', 'refrigerator', 'NR-E473TL'),
  ('Panasonic', 'refrigerator', 'NR-F433T'),
  ('Panasonic', 'refrigerator', 'NR-F434T'),
  ('Panasonic', 'refrigerator', 'NR-F436T'),
  ('Panasonic', 'refrigerator', 'NR-F505XV'),
  ('Panasonic', 'refrigerator', 'NR-F618TV'),
  ('Panasonic', 'refrigerator', 'NR-F555XV'),
  ('Panasonic', 'refrigerator', 'NR-E437T'),
  ('Panasonic', 'refrigerator', 'NR-B253T'),
  ('三菱電機', 'refrigerator', 'MR-RX52T'),
  ('Panasonic', 'refrigerator', 'NR-E474T'),
  ('Panasonic', 'refrigerator', 'NR-F438T'),
  ('Panasonic', 'refrigerator', 'NR-F557XV'),
  ('三菱電機', 'refrigerator', 'MR-RX47T'),
  ('三菱電機', 'refrigerator', 'MR-RX62T'),
  ('三菱電機', 'refrigerator', 'MR-JX52C'),
  ('三菱電機', 'refrigerator', 'MR-JX60C'),
  ('三菱電機', 'refrigerator', 'MR-MX50F'),
  ('三菱電機', 'refrigerator', 'MR-RX46C'),
  ('三菱電機', 'refrigerator', 'MR-WX70A'),
  ('三菱電機', 'refrigerator', 'MR-E47S'),
  ('Panasonic', 'refrigerator', 'NR-F507XV'),
  ('Panasonic', 'refrigerator', 'NR-E474TL'),
  ('Panasonic', 'refrigerator', 'NR-F501XV'),
  ('Panasonic', 'refrigerator', 'NR-F601XV'),
  ('Panasonic', 'refrigerator', 'NR-F604T'),
  ('Panasonic', 'refrigerator', 'NR-F606XV'),
  ('Panasonic', 'refrigerator', 'NR-F603T'),
  ('Panasonic', 'refrigerator', 'NR-F605XV'),
  ('Panasonic', 'refrigerator', 'NR-E436T'),
  ('Panasonic', 'refrigerator', 'NR-F475XPV'),
  ('Panasonic', 'refrigerator', 'NR-F476XPV'),
  ('Panasonic', 'refrigerator', 'NR-F486MEX'),
  ('Panasonic', 'refrigerator', 'NR-F552XPV'),
  ('日立', 'refrigerator', 'R-A5700'),
  ('日立', 'refrigerator', 'R-A6200'),
  ('三菱電機', 'refrigerator', 'MR-RX57T'),
  ('三菱電機', 'refrigerator', 'MR-B46F'),
  ('三菱電機', 'refrigerator', 'MR-MX46H'),
  ('三菱電機', 'refrigerator', 'MR-MX50H'),
  ('三菱電機', 'refrigerator', 'MR-WX47H'),
  ('三菱電機', 'refrigerator', 'MR-WX60A'),
  ('三菱電機', 'refrigerator', 'MR-E52S'),
  ('三菱電機', 'refrigerator', 'MR-R47Y'),
  ('Panasonic', 'refrigerator', 'NR-F500T'),
  ('Panasonic', 'refrigerator', 'NR-E450TL'),
  ('Panasonic', 'refrigerator', 'NR-E415PV'),
  ('Panasonic', 'refrigerator', 'NR-E415PVL'),
  ('Panasonic', 'refrigerator', 'NR-F504HPX'),
  ('Panasonic', 'refrigerator', 'NR-F505HPX'),
  ('Panasonic', 'refrigerator', 'NR-F506XPV'),
  ('シャープ', 'vacuum', 'EC-SR10'),
  ('ダイソン', 'vacuum', 'V8 Absolute'),
  ('日立', 'vacuum', 'PV-BEH900'),
  ('シャープ', 'vacuum', 'EC-AR8'),
  ('シャープ', 'vacuum', 'EC-HR7'),
  ('シャープ', 'vacuum', 'EC-HR8'),
  ('シャープ', 'vacuum', 'EC-SR7'),
  ('シャープ', 'vacuum', 'EC-SR8'),
  ('シャープ', 'vacuum', 'EC-SR9'),
  ('日立', 'vacuum', 'PV-BFL1'),
  ('シャープ', 'vacuum', 'EC-KR1'),
  ('シャープ', 'vacuum', 'EC-AR10'),
  ('シャープ', 'vacuum', 'EC-SX200'),
  ('シャープ', 'vacuum', 'EC-FR9'),
  ('シャープ', 'vacuum', 'EC-PR9'),
  ('シャープ', 'vacuum', 'EC-A1R'),
  ('シャープ', 'vacuum', 'EC-SX530'),
  ('シャープ', 'vacuum', 'EC-AR5'),
  ('シャープ', 'vacuum', 'EC-AR9'),
  ('シャープ', 'vacuum', 'EC-SR5'),
  ('シャープ', 'vacuum', 'EC-AR5X'),
  ('シャープ', 'vacuum', 'EC-FR7'),
  ('日立', 'vacuum', 'PV-BH900H'),
  ('ダイソン', 'vacuum', 'V7 Absolute'),
  ('Panasonic', 'vacuum', 'MC-SB34J'),
  ('日立', 'vacuum', 'PV-BL30H'),
  ('日立', 'vacuum', 'PV-BL10G'),
  ('シャープ', 'vacuum', 'EC-AP700'),
  ('シャープ', 'vacuum', 'EC-AS700'),
  ('Panasonic', 'vacuum', 'MC-SB53K'),
  ('Panasonic', 'vacuum', 'MC-PB60J'),
  ('Panasonic', 'vacuum', 'MC-SB54K'),
  ('日立', 'vacuum', 'PV-BL30K'),
  ('日立', 'vacuum', 'PV-BL50K'),
  ('日立', 'vacuum', 'PV-BHL1000J'),
  ('日立', 'vacuum', 'PV-BHL2000J'),
  ('日立', 'vacuum', 'PV-BHL3000J'),
  ('日立', 'vacuum', 'PV-BKL11G'),
  ('日立', 'vacuum', 'PV-BL1H'),
  ('日立', 'vacuum', 'PV-BL20G'),
  ('日立', 'vacuum', 'PV-BL3J'),
  ('ダイソン', 'vacuum', 'V8 Slim'),
  ('日立', 'vacuum', 'PV-BL30L'),
  ('日立', 'vacuum', 'PV-BL50L'),
  ('日立', 'vacuum', 'PV-BL50M'),
  ('日立', 'vacuum', 'PV-BL2H'),
  ('日立', 'vacuum', 'PV-BH500H'),
  ('シャープ', 'vacuum', 'EC-FR11'),
  ('日立', 'vacuum', 'PV-BEH900009'),
  ('日立', 'vacuum', 'PV-BH900J'),
  ('ダイソン', 'vacuum', 'V6 Absolute'),
  ('シャープ', 'vacuum', 'EC-KH7X'),
  ('日立', 'vacuum', 'PV-BL50G'),
  ('日立', 'vacuum', 'PV-BL50P'),
  ('日立', 'vacuum', 'PV-BH900K'),
  ('日立', 'vacuum', 'PV-BFL1008'),
  ('シャープ', 'vacuum', 'EC-KR3'),
  ('日立', 'vacuum', 'PV-BL3L'),
  ('日立', 'vacuum', 'PV-BKL11L'),
  ('三菱電機', 'rice_cooker', 'NJ-BW10H'),
  ('Panasonic', 'rice_cooker', 'SR-SPA107'),
  ('Panasonic', 'rice_cooker', 'SR-PA107'),
  ('Panasonic', 'rice_cooker', 'SR-PA108'),
  ('Panasonic', 'rice_cooker', 'SR-PA106'),
  ('Panasonic', 'rice_cooker', 'SR-PA109'),
  ('Panasonic', 'rice_cooker', 'SR-SPA108'),
  ('Panasonic', 'rice_cooker', 'SR-PW108'),
  ('Panasonic', 'rice_cooker', 'SR-PW188'),
  ('Panasonic', 'rice_cooker', 'SR-SPA188'),
  ('Panasonic', 'rice_cooker', 'SR-VSX180'),
  ('Panasonic', 'rice_cooker', 'SR-VSX181'),
  ('Panasonic', 'rice_cooker', 'SR-VSX188'),
  ('Panasonic', 'rice_cooker', 'SR-VSX189'),
  ('Panasonic', 'rice_cooker', 'SR-HX185'),
  ('Panasonic', 'rice_cooker', 'SR-HX186'),
  ('象印', 'rice_cooker', 'NW-YA10'),
  ('象印', 'rice_cooker', 'NW-VA10'),
  ('象印', 'rice_cooker', 'NP-VD10'),
  ('象印', 'rice_cooker', 'NW-PS10'),
  ('象印', 'rice_cooker', 'NW-PT10'),
  ('象印', 'rice_cooker', 'NW-QA18'),
  ('東芝', 'rice_cooker', 'RC-108VSS'),
  ('東芝', 'rice_cooker', 'RC-109VSS'),
  ('東芝', 'rice_cooker', 'RC-10VRP'),
  ('東芝', 'rice_cooker', 'RC-10VSP'),
  ('東芝', 'rice_cooker', 'RC-10VSR'),
  ('東芝', 'rice_cooker', 'RC-10VRR'),
  ('三菱電機', 'rice_cooker', 'NJ-VW109'),
  ('三菱電機', 'rice_cooker', 'NJ-SW065'),
  ('三菱電機', 'rice_cooker', 'NJ-SW066'),
  ('三菱電機', 'rice_cooker', 'NJ-SW067'),
  ('三菱電機', 'rice_cooker', 'NJ-SW069'),
  ('日立', 'rice_cooker', 'RZ-WG10M'),
  ('日立', 'rice_cooker', 'RZ-TS180M'),
  ('Panasonic', 'rice_cooker', 'SR-PGC54A'),
  ('象印', 'rice_cooker', 'NP-VI10'),
  ('象印', 'rice_cooker', 'NP-VL10'),
  ('象印', 'rice_cooker', 'NP-VN10'),
  ('象印', 'rice_cooker', 'NP-VZ10'),
  ('象印', 'rice_cooker', 'NP-HQ10'),
  ('タイガー魔法瓶', 'rice_cooker', 'JPB1865'),
  ('タイガー魔法瓶', 'rice_cooker', 'JPB-R180W'),
  ('東芝', 'rice_cooker', 'RC-6XJ'),
  ('東芝', 'rice_cooker', 'RC-6XK'),
  ('東芝', 'rice_cooker', 'RC-6XL'),
  ('東芝', 'rice_cooker', 'RC-6XM'),
  ('三菱電機', 'rice_cooker', 'NJ-SW068'),
  ('三菱電機', 'rice_cooker', 'NJ-VW107'),
  ('三菱電機', 'rice_cooker', 'NJ-SWB06'),
  ('三菱電機', 'rice_cooker', 'NJ-VP10H'),
  ('日立', 'rice_cooker', 'RZ-WV100M'),
  ('日立', 'rice_cooker', 'RZ-BV100M'),
  ('日立', 'rice_cooker', 'RZ-FZ10J'),
  ('日立', 'rice_cooker', 'RZ-SD10KSJ'),
  ('日立', 'rice_cooker', 'RZ-TD10KSJ'),
  ('Panasonic', 'rice_cooker', 'SR-HBA101'),
  ('Panasonic', 'rice_cooker', 'SR-MPW101'),
  ('Panasonic', 'rice_cooker', 'SR-MPW102'),
  ('Panasonic', 'rice_cooker', 'SR-MPW100'),
  ('Panasonic', 'rice_cooker', 'SR-SA182'),
  ('Panasonic', 'rice_cooker', 'SR-SB182'),
  ('Panasonic', 'rice_cooker', 'SR-JX056'),
  ('象印', 'rice_cooker', 'NP-BG10'),
  ('象印', 'rice_cooker', 'NP-BH10'),
  ('象印', 'rice_cooker', 'NP-BJ10'),
  ('象印', 'rice_cooker', 'NW-VA18'),
  ('象印', 'rice_cooker', 'NP-VD18'),
  ('象印', 'rice_cooker', 'NW-FB18'),
  ('象印', 'rice_cooker', 'NW-FA10'),
  ('象印', 'rice_cooker', 'NW-FA18'),
  ('象印', 'rice_cooker', 'NW-WA18'),
  ('象印', 'rice_cooker', 'NP-RU05'),
  ('象印', 'rice_cooker', 'NP-RT05'),
  ('タイガー魔法瓶', 'rice_cooker', 'JPC-B100K'),
  ('タイガー魔法瓶', 'rice_cooker', 'JPC-B100W'),
  ('東芝', 'rice_cooker', 'RC-18VQL'),
  ('東芝', 'rice_cooker', 'RC-18VQM'),
  ('東芝', 'rice_cooker', 'RC-10MSL'),
  ('三菱電機', 'rice_cooker', 'NJ-VW108'),
  ('三菱電機', 'rice_cooker', 'NJ-SWD06'),
  ('三菱電機', 'rice_cooker', 'NJ-VP18G'),
  ('日立', 'rice_cooker', 'RZ-SX100J'),
  ('日立', 'rice_cooker', 'RZ-XC10M'),
  ('日立', 'air_conditioner', 'RAS-VJ4026D'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZXV222'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZXV252'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZXV282S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZXV282'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZXV362S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZXV362'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZXV402S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZXV632S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZXV712S'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV257'),
  ('Panasonic', 'air_conditioner', 'CS-X229C'),
  ('三菱電機', 'air_conditioner', 'MSZ-BXV2218'),
  ('三菱電機', 'air_conditioner', 'MSZ-BXV2518'),
  ('三菱電機', 'air_conditioner', 'MSZ-BXV2818'),
  ('三菱電機', 'air_conditioner', 'MSZ-BXV3618'),
  ('三菱電機', 'air_conditioner', 'MSZ-BXV4018S'),
  ('三菱電機', 'air_conditioner', 'MSZ-BXV5618S'),
  ('三菱電機', 'air_conditioner', 'MSZ-HXV251'),
  ('三菱電機', 'air_conditioner', 'MSZ-HXV252'),
  ('三菱電機', 'air_conditioner', 'MSZ-HXV281S'),
  ('三菱電機', 'air_conditioner', 'MSZ-HXV282S'),
  ('三菱電機', 'air_conditioner', 'MSZ-HXV401S'),
  ('三菱電機', 'air_conditioner', 'MSZ-HXV402S'),
  ('三菱電機', 'air_conditioner', 'MSZ-HXV561S'),
  ('三菱電機', 'air_conditioner', 'MSZ-HXV562S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW221'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW251'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW281S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW281'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW361S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW361'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW401S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW561S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW711S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZXV221'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZXV251'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZXV281S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZXV281'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZXV361S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZXV361'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZXV401S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZXV561S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZXV631S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZXV711S'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV2216'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV225'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV2516'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV255'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV2816S'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV2816'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV285S'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV285'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV3616S'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV3616'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV365S'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV365'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV4016S'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV405S'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV5616S'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV565S'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV6316S'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV7116S'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV227'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV287'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV367'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV407S'),
  ('三菱電機', 'air_conditioner', 'MSZ-JXV507S'),
  ('Panasonic', 'air_conditioner', 'CS-XS400D2'),
  ('Panasonic', 'air_conditioner', 'CS-XS800D2'),
  ('Panasonic', 'air_conditioner', 'CS-XS360D'),
  ('Panasonic', 'air_conditioner', 'CS-XS258C'),
  ('Panasonic', 'air_conditioner', 'CS-XS288C2'),
  ('Panasonic', 'air_conditioner', 'CS-X718C2'),
  ('Panasonic', 'air_conditioner', 'CS-XS408C2'),
  ('Panasonic', 'air_conditioner', 'CS-XS808C2'),
  ('Panasonic', 'air_conditioner', 'CS-XS368C'),
  ('Panasonic', 'air_conditioner', 'CS-X408C2'),
  ('Panasonic', 'air_conditioner', 'CS-XS638C2'),
  ('Panasonic', 'air_conditioner', 'CS-X808C2'),
  ('Panasonic', 'air_conditioner', 'CS-X408C'),
  ('Panasonic', 'air_conditioner', 'CS-XS288C'),
  ('Panasonic', 'air_conditioner', 'CS-X288CZ'),
  ('Panasonic', 'air_conditioner', 'CS-X638C2'),
  ('Panasonic', 'air_conditioner', 'CS-X368C'),
  ('日立', 'air_conditioner', 'RAS-AJ22F'),
  ('日立', 'air_conditioner', 'RAS-MJ7126D'),
  ('Panasonic', 'air_conditioner', 'CS-X569C2'),
  ('Panasonic', 'air_conditioner', 'CS-X409C2'),
  ('Panasonic', 'air_conditioner', 'CS-X809C2'),
  ('日立', 'air_conditioner', 'RAS-VL6325D'),
  ('三菱電機', 'air_conditioner', 'MSZ-NXV5619S'),
  ('三菱電機', 'air_conditioner', 'MSZ-HXV7118S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW631S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZXV562S'),
  ('Panasonic', 'air_conditioner', 'CS-XS400D'),
  ('Panasonic', 'air_conditioner', 'CS-XS710D2'),
  ('Panasonic', 'air_conditioner', 'CS-XS250D'),
  ('Panasonic', 'air_conditioner', 'CS-XS280D2'),
  ('日立', 'air_conditioner', 'RAS-VJ4025D'),
  ('三菱電機', 'air_conditioner', 'MSZ-HXV2516'),
  ('三菱電機', 'air_conditioner', 'MSZ-HXV2816S'),
  ('三菱電機', 'air_conditioner', 'MSZ-HXV4016S'),
  ('三菱電機', 'air_conditioner', 'MSZ-HXV5616S'),
  ('三菱電機', 'air_conditioner', 'MSZ-HXV6316S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW714S'),
  ('三菱電機', 'air_conditioner', 'MSZ-ZW227'),
  ('Panasonic', 'air_conditioner', 'CS-XS908C2'),
  ('Panasonic', 'air_conditioner', 'CS-X289C'),
  ('Panasonic', 'air_conditioner', 'CS-X908C2'),
  ('Panasonic', 'air_conditioner', 'CS-X909C2'),
  ('Panasonic', 'air_conditioner', 'CS-XS228C'),
  ('Panasonic', 'air_conditioner', 'CS-XS368C2'),
  ('Panasonic', 'air_conditioner', 'CS-XS568C2'),
  ('Panasonic', 'air_conditioner', 'CS-X639C2'),
  ('Panasonic', 'air_conditioner', 'CS-X719C2'),
  ('Panasonic', 'air_conditioner', 'CS-X568C2'),
  ('Panasonic', 'air_conditioner', 'CS-X409C'),
  ('Panasonic', 'air_conditioner', 'CS-XS718C2'),
  ('Panasonic', 'air_conditioner', 'CS-XS408C'),
  ('東芝', 'microwave', 'ER-MD7'),
  ('東芝', 'microwave', 'ER-N6'),
  ('東芝', 'microwave', 'ER-N6E'),
  ('東芝', 'microwave', 'ER-ND7'),
  ('東芝', 'microwave', 'ER-P6'),
  ('東芝', 'microwave', 'ER-P6E'),
  ('東芝', 'microwave', 'ER-PD7'),
  ('東芝', 'microwave', 'ER-R6'),
  ('東芝', 'microwave', 'ER-R6E'),
  ('東芝', 'microwave', 'ER-RD7'),
  ('東芝', 'microwave', 'ER-S60'),
  ('東芝', 'microwave', 'ER-S60E'),
  ('東芝', 'microwave', 'ER-SD70'),
  ('東芝', 'microwave', 'ER-T60'),
  ('東芝', 'microwave', 'ER-TD70'),
  ('東芝', 'microwave', 'ER-TD80'),
  ('東芝', 'microwave', 'ER-TD80E'),
  ('東芝', 'microwave', 'ER-VD80'),
  ('東芝', 'microwave', 'ER-W60'),
  ('東芝', 'microwave', 'ER-W60E'),
  ('東芝', 'microwave', 'ER-V60'),
  ('東芝', 'microwave', 'ER-V60E'),
  ('東芝', 'microwave', 'ER-X60'),
  ('東芝', 'microwave', 'ER-XD80'),
  ('東芝', 'microwave', 'ER-ND300'),
  ('シャープ', 'microwave', 'AX-CX2'),
  ('シャープ', 'microwave', 'AX-CX3'),
  ('シャープ', 'microwave', 'AX-G1'),
  ('シャープ', 'microwave', 'AX-HC1'),
  ('シャープ', 'microwave', 'AX-M1'),
  ('シャープ', 'microwave', 'AX-MX1'),
  ('シャープ', 'microwave', 'AX-S1'),
  ('シャープ', 'microwave', 'AX-X1'),
  ('シャープ', 'microwave', 'AX-X2'),
  ('シャープ', 'microwave', 'AX-LSX3A'),
  ('シャープ', 'microwave', 'AX-XA30'),
  ('Panasonic', 'microwave', 'NE-M152'),
  ('Panasonic', 'microwave', 'NE-T152'),
  ('Panasonic', 'microwave', 'NE-T154'),
  ('Panasonic', 'microwave', 'NE-T155'),
  ('Panasonic', 'microwave', 'NE-S420F'),
  ('Panasonic', 'microwave', 'NE-EH227'),
  ('Panasonic', 'microwave', 'NE-TH227'),
  ('Panasonic', 'microwave', 'NE-BS656'),
  ('Panasonic', 'microwave', 'NE-BS808'),
  ('Panasonic', 'microwave', 'NE-BS1500'),
  ('日立', 'microwave', 'MRO-N550'),
  ('日立', 'microwave', 'MRO-CV200'),
  ('日立', 'microwave', 'MRO-GV300'),
  ('日立', 'microwave', 'MRO-JV300'),
  ('日立', 'microwave', 'MRO-CS8'),
  ('日立', 'microwave', 'MRO-RY3000'),
  ('日立', 'microwave', 'MRO-SBK1'),
  ('日立', 'microwave', 'MRO-SF6'),
  ('日立', 'microwave', 'MRO-SV3000'),
  ('東芝', 'microwave', 'ER-M6E'),
  ('東芝', 'microwave', 'ER-F3'),
  ('東芝', 'microwave', 'ER-GE54'),
  ('東芝', 'microwave', 'ER-H3'),
  ('東芝', 'microwave', 'ER-J3'),
  ('東芝', 'microwave', 'ER-J3A'),
  ('東芝', 'microwave', 'ER-K3'),
  ('東芝', 'microwave', 'ER-YJ3'),
  ('東芝', 'microwave', 'ER-YJ3A'),
  ('東芝', 'microwave', 'ER-YK3'),
  ('東芝', 'microwave', 'ER-H10'),
  ('東芝', 'microwave', 'ER-SD100'),
  ('東芝', 'microwave', 'ER-JD310'),
  ('東芝', 'microwave', 'ER-JD310A'),
  ('東芝', 'microwave', 'ER-JD410'),
  ('東芝', 'microwave', 'ER-JD410A'),
  ('東芝', 'microwave', 'ER-JD510'),
  ('東芝', 'microwave', 'ER-JD510A'),
  ('東芝', 'microwave', 'ER-KD320'),
  ('東芝', 'microwave', 'ER-KD420'),
  ('東芝', 'microwave', 'ER-KD520'),
  ('東芝', 'microwave', 'ER-LD330'),
  ('東芝', 'microwave', 'ER-LD430'),
  ('東芝', 'microwave', 'ER-LD530'),
  ('東芝', 'microwave', 'ER-WD3000'),
  ('シャープ', 'microwave', 'AX-GX2'),
  ('シャープ', 'microwave', 'AX-PX1'),
  ('シャープ', 'microwave', 'AX-PX2'),
  ('Panasonic', 'microwave', 'NE-EH2'),
  ('Panasonic', 'microwave', 'NE-EH22'),
  ('Panasonic', 'microwave', 'NE-EZ2'),
  ('Panasonic', 'microwave', 'NE-S200F'),
  ('Panasonic', 'microwave', 'NE-EH212'),
  ('Panasonic', 'microwave', 'NE-EH228'),
  ('Panasonic', 'microwave', 'NE-TH224'),
  ('Panasonic', 'microwave', 'NE-TH228'),
  ('Panasonic', 'microwave', 'NE-BS658'),
  ('Panasonic', 'microwave', 'NE-BS6A'),
  ('Panasonic', 'microwave', 'NE-BS655'),
  ('Panasonic', 'microwave', 'NE-BS9C'),
  ('Panasonic', 'microwave', 'NE-JBS652'),
  ('Panasonic', 'microwave', 'NE-JBS653'),
  ('Panasonic', 'microwave', 'NE-JBS654'),
  ('Panasonic', 'microwave', 'NE-SBS656'),
  ('Panasonic', 'microwave', 'NE-UBS10C')
on conflict (manufacturer, model_number) do nothing;

insert into parts (name, category, kind, manufacturer) values
  ('糸くずフィルター ES-LP2', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-LP1', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-PX8C', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-PX8D', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TX840', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GX850', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GX8A', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-PX8B', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TX830', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター NA-FA120V1', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA70H2', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA70H3', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA80H2', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA80H3', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA80H5', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA80H6', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA90H6', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA90H5', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA100H7', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA80H7', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA90H7', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA120V2', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA100H9', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA10K1', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA80H9', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA90H9', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA100H8', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA80H8', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FW100K9', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター ES-GE7A', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TX74', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター BW-D10WV', 'filter', 'oem', '日立'),
  ('糸くずフィルター BW-D10XTV', 'filter', 'oem', '日立'),
  ('糸くずフィルター ES-GE60P', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GE70R', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GE7B', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GE7C', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GE7D', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-PW10D', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター NA-FW100K8', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA120V3', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター NA-FA90H8', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター ES-GE60N', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GV8A', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GV9B', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GV9C', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-KSV9C', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-PT10C', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-PT10D', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-PU10C', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-PU11B', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-PU11C', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-PW11D', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-PW8D', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-PX10A', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-PX10B', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-PX9B', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-T707', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-T708', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-T711', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TX8A', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TX8B', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TX8C', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TX930', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TX940', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TX9A', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター NA-F70PB15', 'filter', 'oem', 'Panasonic'),
  ('糸くずフィルター ES-GE70N', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GE70P', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GV10B', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GV10C', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GV10D', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GV80R', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GV8B', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GV8C', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GV8D', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GV90R', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GV9A', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GV9D', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GW11D', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GX950', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GX9A', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-KS70P', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-KS70R', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-KS70S', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-KS70U', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-T706', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TX8D', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-GE55N', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-KS70N', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-KSV9B', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-KSV9D', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-T709', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-T710', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TA840', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TX750', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TX850', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TX950', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター ES-TG74V', 'filter', 'oem', 'シャープ'),
  ('糸くずフィルター NA-F60PB12', 'filter', 'oem', 'Panasonic'),
  ('製氷皿 MR-WX53Z', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-JX53Z', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-WX48Z', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-WX61Z', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-B46Z', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-JX61Z', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-WX70C', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-WX71Z', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-JX53X', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-JX52W', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-JX53Y', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 GR-M15BS', 'ice_tray', 'oem', '東芝'),
  ('製氷皿 NR-F561XPV', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 MR-JX60W', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-B46D', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-MB45E', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-MX57D', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-RX46A', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-WX61Y', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-WX71Y', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 NR-E438T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F605T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 R-B6700', 'ice_tray', 'oem', '日立'),
  ('製氷皿 MR-JX64W', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-JX52A', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-JX60A', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-MX50D', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-JX61X', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-JX61Y', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 GR-M17BS', 'ice_tray', 'oem', '東芝'),
  ('製氷皿 GR-P15BS', 'ice_tray', 'oem', '東芝'),
  ('製氷皿 GR-P17BS', 'ice_tray', 'oem', '東芝'),
  ('製氷皿 GR-R15BS', 'ice_tray', 'oem', '東芝'),
  ('製氷皿 GR-R17BS', 'ice_tray', 'oem', '東芝'),
  ('製氷皿 GR-S15BS', 'ice_tray', 'oem', '東芝'),
  ('製氷皿 GR-S17BS', 'ice_tray', 'oem', '東芝'),
  ('製氷皿 GR-T15BS', 'ice_tray', 'oem', '東芝'),
  ('製氷皿 GR-T17BS', 'ice_tray', 'oem', '東芝'),
  ('製氷皿 GR-U15BS', 'ice_tray', 'oem', '東芝'),
  ('製氷皿 GR-U17BS', 'ice_tray', 'oem', '東芝'),
  ('製氷皿 GR-V15BS', 'ice_tray', 'oem', '東芝'),
  ('製氷皿 GR-V17BS', 'ice_tray', 'oem', '東芝'),
  ('製氷皿 NR-E434T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F506XV', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 GR-G51FXV', 'ice_tray', 'oem', '東芝'),
  ('製氷皿 GR-P510FD', 'ice_tray', 'oem', '東芝'),
  ('製氷皿 NR-E434TL', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-E435T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-E435TL', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-E473TL', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F433T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F434T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F436T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F505XV', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F618TV', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F555XV', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-E437T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-B253T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 MR-RX52T', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 NR-E474T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F438T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F557XV', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 MR-RX47T', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-RX62T', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-JX52C', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-JX60C', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-MX50F', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-RX46C', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-WX70A', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-E47S', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 NR-F507XV', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-E474TL', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F501XV', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F601XV', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F604T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F606XV', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F603T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F605XV', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-E436T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F475XPV', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F476XPV', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F486MEX', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F552XPV', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 R-A5700', 'ice_tray', 'oem', '日立'),
  ('製氷皿 R-A6200', 'ice_tray', 'oem', '日立'),
  ('製氷皿 MR-RX57T', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-B46F', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-MX46H', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-MX50H', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-WX47H', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-WX60A', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-E52S', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 MR-R47Y', 'ice_tray', 'oem', '三菱電機'),
  ('製氷皿 NR-F500T', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-E450TL', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-E415PV', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-E415PVL', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F504HPX', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F505HPX', 'ice_tray', 'oem', 'Panasonic'),
  ('製氷皿 NR-F506XPV', 'ice_tray', 'oem', 'Panasonic'),
  ('バッテリー EC-SR10', 'battery', 'oem', 'シャープ'),
  ('バッテリー V8 Absolute', 'battery', 'oem', 'ダイソン'),
  ('バッテリー PV-BEH900', 'battery', 'oem', '日立'),
  ('バッテリー EC-AR8', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-HR7', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-HR8', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-SR7', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-SR8', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-SR9', 'battery', 'oem', 'シャープ'),
  ('バッテリー PV-BFL1', 'battery', 'oem', '日立'),
  ('バッテリー EC-KR1', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-AR10', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-SX200', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-FR9', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-PR9', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-A1R', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-SX530', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-AR5', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-AR9', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-SR5', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-AR5X', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-FR7', 'battery', 'oem', 'シャープ'),
  ('バッテリー PV-BH900H', 'battery', 'oem', '日立'),
  ('バッテリー V7 Absolute', 'battery', 'oem', 'ダイソン'),
  ('バッテリー MC-SB34J', 'battery', 'oem', 'Panasonic'),
  ('バッテリー PV-BL30H', 'battery', 'oem', '日立'),
  ('バッテリー PV-BL10G', 'battery', 'oem', '日立'),
  ('バッテリー EC-AP700', 'battery', 'oem', 'シャープ'),
  ('バッテリー EC-AS700', 'battery', 'oem', 'シャープ'),
  ('バッテリー MC-SB53K', 'battery', 'oem', 'Panasonic'),
  ('バッテリー MC-PB60J', 'battery', 'oem', 'Panasonic'),
  ('バッテリー MC-SB54K', 'battery', 'oem', 'Panasonic'),
  ('バッテリー PV-BL30K', 'battery', 'oem', '日立'),
  ('バッテリー PV-BL50K', 'battery', 'oem', '日立'),
  ('バッテリー PV-BHL1000J', 'battery', 'oem', '日立'),
  ('バッテリー PV-BHL2000J', 'battery', 'oem', '日立'),
  ('バッテリー PV-BHL3000J', 'battery', 'oem', '日立'),
  ('バッテリー PV-BKL11G', 'battery', 'oem', '日立'),
  ('バッテリー PV-BL1H', 'battery', 'oem', '日立'),
  ('バッテリー PV-BL20G', 'battery', 'oem', '日立'),
  ('バッテリー PV-BL3J', 'battery', 'oem', '日立'),
  ('バッテリー V8 Slim', 'battery', 'oem', 'ダイソン'),
  ('バッテリー PV-BL30L', 'battery', 'oem', '日立'),
  ('バッテリー PV-BL50L', 'battery', 'oem', '日立'),
  ('バッテリー PV-BL50M', 'battery', 'oem', '日立'),
  ('バッテリー PV-BL2H', 'battery', 'oem', '日立'),
  ('バッテリー PV-BH500H', 'battery', 'oem', '日立'),
  ('バッテリー EC-FR11', 'battery', 'oem', 'シャープ'),
  ('バッテリー PV-BEH900009', 'battery', 'oem', '日立'),
  ('バッテリー PV-BH900J', 'battery', 'oem', '日立'),
  ('バッテリー V6 Absolute', 'battery', 'oem', 'ダイソン'),
  ('バッテリー EC-KH7X', 'battery', 'oem', 'シャープ'),
  ('バッテリー PV-BL50G', 'battery', 'oem', '日立'),
  ('バッテリー PV-BL50P', 'battery', 'oem', '日立'),
  ('バッテリー PV-BH900K', 'battery', 'oem', '日立'),
  ('バッテリー PV-BFL1008', 'battery', 'oem', '日立'),
  ('バッテリー EC-KR3', 'battery', 'oem', 'シャープ'),
  ('バッテリー PV-BL3L', 'battery', 'oem', '日立'),
  ('バッテリー PV-BKL11L', 'battery', 'oem', '日立'),
  ('内釜 NJ-BW10H', 'inner_pot', 'oem', '三菱電機'),
  ('内釜 SR-SPA107', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-PA107', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-PA108', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-PA106', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-PA109', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-SPA108', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-PW108', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-PW188', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-SPA188', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-VSX180', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-VSX181', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-VSX188', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-VSX189', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-HX185', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-HX186', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 NW-YA10', 'inner_pot', 'oem', '象印'),
  ('内釜 NW-VA10', 'inner_pot', 'oem', '象印'),
  ('内釜 NP-VD10', 'inner_pot', 'oem', '象印'),
  ('内釜 NW-PS10', 'inner_pot', 'oem', '象印'),
  ('内釜 NW-PT10', 'inner_pot', 'oem', '象印'),
  ('内釜 NW-QA18', 'inner_pot', 'oem', '象印'),
  ('内釜 RC-108VSS', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-109VSS', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-10VRP', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-10VSP', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-10VSR', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-10VRR', 'inner_pot', 'oem', '東芝'),
  ('内釜 NJ-VW109', 'inner_pot', 'oem', '三菱電機'),
  ('内釜 NJ-SW065', 'inner_pot', 'oem', '三菱電機'),
  ('内釜 NJ-SW066', 'inner_pot', 'oem', '三菱電機'),
  ('内釜 NJ-SW067', 'inner_pot', 'oem', '三菱電機'),
  ('内釜 NJ-SW069', 'inner_pot', 'oem', '三菱電機'),
  ('内釜 RZ-WG10M', 'inner_pot', 'oem', '日立'),
  ('内釜 RZ-TS180M', 'inner_pot', 'oem', '日立'),
  ('内釜 SR-PGC54A', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 NP-VI10', 'inner_pot', 'oem', '象印'),
  ('内釜 NP-VL10', 'inner_pot', 'oem', '象印'),
  ('内釜 NP-VN10', 'inner_pot', 'oem', '象印'),
  ('内釜 NP-VZ10', 'inner_pot', 'oem', '象印'),
  ('内釜 NP-HQ10', 'inner_pot', 'oem', '象印'),
  ('内釜 JPB1865', 'inner_pot', 'oem', 'タイガー魔法瓶'),
  ('内釜 JPB-R180W', 'inner_pot', 'oem', 'タイガー魔法瓶'),
  ('内釜 RC-6XJ', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-6XK', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-6XL', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-6XM', 'inner_pot', 'oem', '東芝'),
  ('内釜 NJ-SW068', 'inner_pot', 'oem', '三菱電機'),
  ('内釜 NJ-VW107', 'inner_pot', 'oem', '三菱電機'),
  ('内釜 NJ-SWB06', 'inner_pot', 'oem', '三菱電機'),
  ('内釜 NJ-VP10H', 'inner_pot', 'oem', '三菱電機'),
  ('内釜 RZ-WV100M', 'inner_pot', 'oem', '日立'),
  ('内釜 RZ-BV100M', 'inner_pot', 'oem', '日立'),
  ('内釜 RZ-FZ10J', 'inner_pot', 'oem', '日立'),
  ('内釜 RZ-SD10KSJ', 'inner_pot', 'oem', '日立'),
  ('内釜 RZ-TD10KSJ', 'inner_pot', 'oem', '日立'),
  ('内釜 SR-HBA101', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-MPW101', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-MPW102', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-MPW100', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-SA182', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-SB182', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 SR-JX056', 'inner_pot', 'oem', 'Panasonic'),
  ('内釜 NP-BG10', 'inner_pot', 'oem', '象印'),
  ('内釜 NP-BH10', 'inner_pot', 'oem', '象印'),
  ('内釜 NP-BJ10', 'inner_pot', 'oem', '象印'),
  ('内釜 NW-VA18', 'inner_pot', 'oem', '象印'),
  ('内釜 NP-VD18', 'inner_pot', 'oem', '象印'),
  ('内釜 NW-FB18', 'inner_pot', 'oem', '象印'),
  ('内釜 NW-FA10', 'inner_pot', 'oem', '象印'),
  ('内釜 NW-FA18', 'inner_pot', 'oem', '象印'),
  ('内釜 NW-WA18', 'inner_pot', 'oem', '象印'),
  ('内釜 NP-RU05', 'inner_pot', 'oem', '象印'),
  ('内釜 NP-RT05', 'inner_pot', 'oem', '象印'),
  ('内釜 JPC-B100K', 'inner_pot', 'oem', 'タイガー魔法瓶'),
  ('内釜 JPC-B100W', 'inner_pot', 'oem', 'タイガー魔法瓶'),
  ('内釜 RC-18VQL', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-18VQM', 'inner_pot', 'oem', '東芝'),
  ('内釜 RC-10MSL', 'inner_pot', 'oem', '東芝'),
  ('内釜 NJ-VW108', 'inner_pot', 'oem', '三菱電機'),
  ('内釜 NJ-SWD06', 'inner_pot', 'oem', '三菱電機'),
  ('内釜 NJ-VP18G', 'inner_pot', 'oem', '三菱電機'),
  ('内釜 RZ-SX100J', 'inner_pot', 'oem', '日立'),
  ('内釜 RZ-XC10M', 'inner_pot', 'oem', '日立'),
  ('フィルター RAS-VJ4026D', 'filter', 'oem', '日立'),
  ('フィルター MSZ-ZXV222', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZXV252', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZXV282S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZXV282', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZXV362S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZXV362', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZXV402S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZXV632S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZXV712S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV257', 'filter', 'oem', '三菱電機'),
  ('フィルター CS-X229C', 'filter', 'oem', 'Panasonic'),
  ('フィルター MSZ-BXV2218', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-BXV2518', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-BXV2818', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-BXV3618', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-BXV4018S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-BXV5618S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-HXV251', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-HXV252', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-HXV281S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-HXV282S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-HXV401S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-HXV402S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-HXV561S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-HXV562S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW221', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW251', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW281S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW281', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW361S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW361', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW401S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW561S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW711S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZXV221', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZXV251', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZXV281S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZXV281', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZXV361S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZXV361', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZXV401S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZXV561S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZXV631S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZXV711S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV2216', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV225', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV2516', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV255', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV2816S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV2816', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV285S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV285', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV3616S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV3616', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV365S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV365', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV4016S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV405S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV5616S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV565S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV6316S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV7116S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV227', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV287', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV367', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV407S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-JXV507S', 'filter', 'oem', '三菱電機'),
  ('フィルター CS-XS400D2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS800D2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS360D', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS258C', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS288C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X718C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS408C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS808C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS368C', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X408C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS638C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X808C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X408C', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS288C', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X288CZ', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X638C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X368C', 'filter', 'oem', 'Panasonic'),
  ('フィルター RAS-AJ22F', 'filter', 'oem', '日立'),
  ('フィルター RAS-MJ7126D', 'filter', 'oem', '日立'),
  ('フィルター CS-X569C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X409C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X809C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター RAS-VL6325D', 'filter', 'oem', '日立'),
  ('フィルター MSZ-NXV5619S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-HXV7118S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW631S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZXV562S', 'filter', 'oem', '三菱電機'),
  ('フィルター CS-XS400D', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS710D2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS250D', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS280D2', 'filter', 'oem', 'Panasonic'),
  ('フィルター RAS-VJ4025D', 'filter', 'oem', '日立'),
  ('フィルター MSZ-HXV2516', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-HXV2816S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-HXV4016S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-HXV5616S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-HXV6316S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW714S', 'filter', 'oem', '三菱電機'),
  ('フィルター MSZ-ZW227', 'filter', 'oem', '三菱電機'),
  ('フィルター CS-XS908C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X289C', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X908C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X909C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS228C', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS368C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS568C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X639C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X719C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X568C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-X409C', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS718C2', 'filter', 'oem', 'Panasonic'),
  ('フィルター CS-XS408C', 'filter', 'oem', 'Panasonic'),
  ('ターンテーブル ER-MD7', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-N6', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-N6E', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-ND7', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-P6', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-P6E', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-PD7', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-R6', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-R6E', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-RD7', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-S60', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-S60E', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-SD70', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-T60', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-TD70', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-TD80', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-TD80E', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-VD80', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-W60', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-W60E', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-V60', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-V60E', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-X60', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-XD80', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-ND300', 'turntable', 'oem', '東芝'),
  ('ターンテーブル AX-CX2', 'turntable', 'oem', 'シャープ'),
  ('ターンテーブル AX-CX3', 'turntable', 'oem', 'シャープ'),
  ('ターンテーブル AX-G1', 'turntable', 'oem', 'シャープ'),
  ('ターンテーブル AX-HC1', 'turntable', 'oem', 'シャープ'),
  ('ターンテーブル AX-M1', 'turntable', 'oem', 'シャープ'),
  ('ターンテーブル AX-MX1', 'turntable', 'oem', 'シャープ'),
  ('ターンテーブル AX-S1', 'turntable', 'oem', 'シャープ'),
  ('ターンテーブル AX-X1', 'turntable', 'oem', 'シャープ'),
  ('ターンテーブル AX-X2', 'turntable', 'oem', 'シャープ'),
  ('ターンテーブル AX-LSX3A', 'turntable', 'oem', 'シャープ'),
  ('ターンテーブル AX-XA30', 'turntable', 'oem', 'シャープ'),
  ('ターンテーブル NE-M152', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-T152', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-T154', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-T155', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-S420F', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-EH227', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-TH227', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-BS656', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-BS808', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-BS1500', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル MRO-N550', 'turntable', 'oem', '日立'),
  ('ターンテーブル MRO-CV200', 'turntable', 'oem', '日立'),
  ('ターンテーブル MRO-GV300', 'turntable', 'oem', '日立'),
  ('ターンテーブル MRO-JV300', 'turntable', 'oem', '日立'),
  ('ターンテーブル MRO-CS8', 'turntable', 'oem', '日立'),
  ('ターンテーブル MRO-RY3000', 'turntable', 'oem', '日立'),
  ('ターンテーブル MRO-SBK1', 'turntable', 'oem', '日立'),
  ('ターンテーブル MRO-SF6', 'turntable', 'oem', '日立'),
  ('ターンテーブル MRO-SV3000', 'turntable', 'oem', '日立'),
  ('ターンテーブル ER-M6E', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-F3', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-GE54', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-H3', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-J3', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-J3A', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-K3', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-YJ3', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-YJ3A', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-YK3', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-H10', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-SD100', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-JD310', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-JD310A', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-JD410', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-JD410A', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-JD510', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-JD510A', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-KD320', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-KD420', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-KD520', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-LD330', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-LD430', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-LD530', 'turntable', 'oem', '東芝'),
  ('ターンテーブル ER-WD3000', 'turntable', 'oem', '東芝'),
  ('ターンテーブル AX-GX2', 'turntable', 'oem', 'シャープ'),
  ('ターンテーブル AX-PX1', 'turntable', 'oem', 'シャープ'),
  ('ターンテーブル AX-PX2', 'turntable', 'oem', 'シャープ'),
  ('ターンテーブル NE-EH2', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-EH22', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-EZ2', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-S200F', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-EH212', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-EH228', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-TH224', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-TH228', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-BS658', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-BS6A', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-BS655', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-BS9C', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-JBS652', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-JBS653', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-JBS654', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-SBS656', 'turntable', 'oem', 'Panasonic'),
  ('ターンテーブル NE-UBS10C', 'turntable', 'oem', 'Panasonic')
on conflict do nothing;

insert into appliance_parts (appliance_id, part_id, fitment_note)
select a.id, p.id, null
from parts p
join appliances a on p.name like '%' || a.model_number
where a.model_number in ('ES-LP2', 'ES-LP1', 'ES-PX8C', 'ES-PX8D', 'ES-TX840', 'ES-GX850', 'ES-GX8A', 'ES-PX8B', 'ES-TX830', 'NA-FA120V1', 'NA-FA70H2', 'NA-FA70H3', 'NA-FA80H2', 'NA-FA80H3', 'NA-FA80H5', 'NA-FA80H6', 'NA-FA90H6', 'NA-FA90H5', 'NA-FA100H7', 'NA-FA80H7', 'NA-FA90H7', 'NA-FA120V2', 'NA-FA100H9', 'NA-FA10K1', 'NA-FA80H9', 'NA-FA90H9', 'NA-FA100H8', 'NA-FA80H8', 'NA-FW100K9', 'ES-GE7A', 'ES-TX74', 'BW-D10WV', 'BW-D10XTV', 'ES-GE60P', 'ES-GE70R', 'ES-GE7B', 'ES-GE7C', 'ES-GE7D', 'ES-PW10D', 'NA-FW100K8', 'NA-FA120V3', 'NA-FA90H8', 'ES-GE60N', 'ES-GV8A', 'ES-GV9B', 'ES-GV9C', 'ES-KSV9C', 'ES-PT10C', 'ES-PT10D', 'ES-PU10C', 'ES-PU11B', 'ES-PU11C', 'ES-PW11D', 'ES-PW8D', 'ES-PX10A', 'ES-PX10B', 'ES-PX9B', 'ES-T707', 'ES-T708', 'ES-T711', 'ES-TX8A', 'ES-TX8B', 'ES-TX8C', 'ES-TX930', 'ES-TX940', 'ES-TX9A', 'NA-F70PB15', 'ES-GE70N', 'ES-GE70P', 'ES-GV10B', 'ES-GV10C', 'ES-GV10D', 'ES-GV80R', 'ES-GV8B', 'ES-GV8C', 'ES-GV8D', 'ES-GV90R', 'ES-GV9A', 'ES-GV9D', 'ES-GW11D', 'ES-GX950', 'ES-GX9A', 'ES-KS70P', 'ES-KS70R', 'ES-KS70S', 'ES-KS70U', 'ES-T706', 'ES-TX8D', 'ES-GE55N', 'ES-KS70N', 'ES-KSV9B', 'ES-KSV9D', 'ES-T709', 'ES-T710', 'ES-TA840', 'ES-TX750', 'ES-TX850', 'ES-TX950', 'ES-TG74V', 'NA-F60PB12', 'MR-WX53Z', 'MR-JX53Z', 'MR-WX48Z', 'MR-WX61Z', 'MR-B46Z', 'MR-JX61Z', 'MR-WX70C', 'MR-WX71Z', 'MR-JX53X', 'MR-JX52W', 'MR-JX53Y', 'GR-M15BS', 'NR-F561XPV', 'MR-JX60W', 'MR-B46D', 'MR-MB45E', 'MR-MX57D', 'MR-RX46A', 'MR-WX61Y', 'MR-WX71Y', 'NR-E438T', 'NR-F605T', 'R-B6700', 'MR-JX64W', 'MR-JX52A', 'MR-JX60A', 'MR-MX50D', 'MR-JX61X', 'MR-JX61Y', 'GR-M17BS', 'GR-P15BS', 'GR-P17BS', 'GR-R15BS', 'GR-R17BS', 'GR-S15BS', 'GR-S17BS', 'GR-T15BS', 'GR-T17BS', 'GR-U15BS', 'GR-U17BS', 'GR-V15BS', 'GR-V17BS', 'NR-E434T', 'NR-F506XV', 'GR-G51FXV', 'GR-P510FD', 'NR-E434TL', 'NR-E435T', 'NR-E435TL', 'NR-E473TL', 'NR-F433T', 'NR-F434T', 'NR-F436T', 'NR-F505XV', 'NR-F618TV', 'NR-F555XV', 'NR-E437T', 'NR-B253T', 'MR-RX52T', 'NR-E474T', 'NR-F438T', 'NR-F557XV', 'MR-RX47T', 'MR-RX62T', 'MR-JX52C', 'MR-JX60C', 'MR-MX50F', 'MR-RX46C', 'MR-WX70A', 'MR-E47S', 'NR-F507XV', 'NR-E474TL', 'NR-F501XV', 'NR-F601XV', 'NR-F604T', 'NR-F606XV', 'NR-F603T', 'NR-F605XV', 'NR-E436T', 'NR-F475XPV', 'NR-F476XPV', 'NR-F486MEX', 'NR-F552XPV', 'R-A5700', 'R-A6200', 'MR-RX57T', 'MR-B46F', 'MR-MX46H', 'MR-MX50H', 'MR-WX47H', 'MR-WX60A', 'MR-E52S', 'MR-R47Y', 'NR-F500T', 'NR-E450TL', 'NR-E415PV', 'NR-E415PVL', 'NR-F504HPX', 'NR-F505HPX', 'NR-F506XPV', 'EC-SR10', 'V8 Absolute', 'PV-BEH900', 'EC-AR8', 'EC-HR7', 'EC-HR8', 'EC-SR7', 'EC-SR8', 'EC-SR9', 'PV-BFL1', 'EC-KR1', 'EC-AR10', 'EC-SX200', 'EC-FR9', 'EC-PR9', 'EC-A1R', 'EC-SX530', 'EC-AR5', 'EC-AR9', 'EC-SR5', 'EC-AR5X', 'EC-FR7', 'PV-BH900H', 'V7 Absolute', 'MC-SB34J', 'PV-BL30H', 'PV-BL10G', 'EC-AP700', 'EC-AS700', 'MC-SB53K', 'MC-PB60J', 'MC-SB54K', 'PV-BL30K', 'PV-BL50K', 'PV-BHL1000J', 'PV-BHL2000J', 'PV-BHL3000J', 'PV-BKL11G', 'PV-BL1H', 'PV-BL20G', 'PV-BL3J', 'V8 Slim', 'PV-BL30L', 'PV-BL50L', 'PV-BL50M', 'PV-BL2H', 'PV-BH500H', 'EC-FR11', 'PV-BEH900009', 'PV-BH900J', 'V6 Absolute', 'EC-KH7X', 'PV-BL50G', 'PV-BL50P', 'PV-BH900K', 'PV-BFL1008', 'EC-KR3', 'PV-BL3L', 'PV-BKL11L', 'NJ-BW10H', 'SR-SPA107', 'SR-PA107', 'SR-PA108', 'SR-PA106', 'SR-PA109', 'SR-SPA108', 'SR-PW108', 'SR-PW188', 'SR-SPA188', 'SR-VSX180', 'SR-VSX181', 'SR-VSX188', 'SR-VSX189', 'SR-HX185', 'SR-HX186', 'NW-YA10', 'NW-VA10', 'NP-VD10', 'NW-PS10', 'NW-PT10', 'NW-QA18', 'RC-108VSS', 'RC-109VSS', 'RC-10VRP', 'RC-10VSP', 'RC-10VSR', 'RC-10VRR', 'NJ-VW109', 'NJ-SW065', 'NJ-SW066', 'NJ-SW067', 'NJ-SW069', 'RZ-WG10M', 'RZ-TS180M', 'SR-PGC54A', 'NP-VI10', 'NP-VL10', 'NP-VN10', 'NP-VZ10', 'NP-HQ10', 'JPB1865', 'JPB-R180W', 'RC-6XJ', 'RC-6XK', 'RC-6XL', 'RC-6XM', 'NJ-SW068', 'NJ-VW107', 'NJ-SWB06', 'NJ-VP10H', 'RZ-WV100M', 'RZ-BV100M', 'RZ-FZ10J', 'RZ-SD10KSJ', 'RZ-TD10KSJ', 'SR-HBA101', 'SR-MPW101', 'SR-MPW102', 'SR-MPW100', 'SR-SA182', 'SR-SB182', 'SR-JX056', 'NP-BG10', 'NP-BH10', 'NP-BJ10', 'NW-VA18', 'NP-VD18', 'NW-FB18', 'NW-FA10', 'NW-FA18', 'NW-WA18', 'NP-RU05', 'NP-RT05', 'JPC-B100K', 'JPC-B100W', 'RC-18VQL', 'RC-18VQM', 'RC-10MSL', 'NJ-VW108', 'NJ-SWD06', 'NJ-VP18G', 'RZ-SX100J', 'RZ-XC10M', 'RAS-VJ4026D', 'MSZ-ZXV222', 'MSZ-ZXV252', 'MSZ-ZXV282S', 'MSZ-ZXV282', 'MSZ-ZXV362S', 'MSZ-ZXV362', 'MSZ-ZXV402S', 'MSZ-ZXV632S', 'MSZ-ZXV712S', 'MSZ-JXV257', 'CS-X229C', 'MSZ-BXV2218', 'MSZ-BXV2518', 'MSZ-BXV2818', 'MSZ-BXV3618', 'MSZ-BXV4018S', 'MSZ-BXV5618S', 'MSZ-HXV251', 'MSZ-HXV252', 'MSZ-HXV281S', 'MSZ-HXV282S', 'MSZ-HXV401S', 'MSZ-HXV402S', 'MSZ-HXV561S', 'MSZ-HXV562S', 'MSZ-ZW221', 'MSZ-ZW251', 'MSZ-ZW281S', 'MSZ-ZW281', 'MSZ-ZW361S', 'MSZ-ZW361', 'MSZ-ZW401S', 'MSZ-ZW561S', 'MSZ-ZW711S', 'MSZ-ZXV221', 'MSZ-ZXV251', 'MSZ-ZXV281S', 'MSZ-ZXV281', 'MSZ-ZXV361S', 'MSZ-ZXV361', 'MSZ-ZXV401S', 'MSZ-ZXV561S', 'MSZ-ZXV631S', 'MSZ-ZXV711S', 'MSZ-JXV2216', 'MSZ-JXV225', 'MSZ-JXV2516', 'MSZ-JXV255', 'MSZ-JXV2816S', 'MSZ-JXV2816', 'MSZ-JXV285S', 'MSZ-JXV285', 'MSZ-JXV3616S', 'MSZ-JXV3616', 'MSZ-JXV365S', 'MSZ-JXV365', 'MSZ-JXV4016S', 'MSZ-JXV405S', 'MSZ-JXV5616S', 'MSZ-JXV565S', 'MSZ-JXV6316S', 'MSZ-JXV7116S', 'MSZ-JXV227', 'MSZ-JXV287', 'MSZ-JXV367', 'MSZ-JXV407S', 'MSZ-JXV507S', 'CS-XS400D2', 'CS-XS800D2', 'CS-XS360D', 'CS-XS258C', 'CS-XS288C2', 'CS-X718C2', 'CS-XS408C2', 'CS-XS808C2', 'CS-XS368C', 'CS-X408C2', 'CS-XS638C2', 'CS-X808C2', 'CS-X408C', 'CS-XS288C', 'CS-X288CZ', 'CS-X638C2', 'CS-X368C', 'RAS-AJ22F', 'RAS-MJ7126D', 'CS-X569C2', 'CS-X409C2', 'CS-X809C2', 'RAS-VL6325D', 'MSZ-NXV5619S', 'MSZ-HXV7118S', 'MSZ-ZW631S', 'MSZ-ZXV562S', 'CS-XS400D', 'CS-XS710D2', 'CS-XS250D', 'CS-XS280D2', 'RAS-VJ4025D', 'MSZ-HXV2516', 'MSZ-HXV2816S', 'MSZ-HXV4016S', 'MSZ-HXV5616S', 'MSZ-HXV6316S', 'MSZ-ZW714S', 'MSZ-ZW227', 'CS-XS908C2', 'CS-X289C', 'CS-X908C2', 'CS-X909C2', 'CS-XS228C', 'CS-XS368C2', 'CS-XS568C2', 'CS-X639C2', 'CS-X719C2', 'CS-X568C2', 'CS-X409C', 'CS-XS718C2', 'CS-XS408C', 'ER-MD7', 'ER-N6', 'ER-N6E', 'ER-ND7', 'ER-P6', 'ER-P6E', 'ER-PD7', 'ER-R6', 'ER-R6E', 'ER-RD7', 'ER-S60', 'ER-S60E', 'ER-SD70', 'ER-T60', 'ER-TD70', 'ER-TD80', 'ER-TD80E', 'ER-VD80', 'ER-W60', 'ER-W60E', 'ER-V60', 'ER-V60E', 'ER-X60', 'ER-XD80', 'ER-ND300', 'AX-CX2', 'AX-CX3', 'AX-G1', 'AX-HC1', 'AX-M1', 'AX-MX1', 'AX-S1', 'AX-X1', 'AX-X2', 'AX-LSX3A', 'AX-XA30', 'NE-M152', 'NE-T152', 'NE-T154', 'NE-T155', 'NE-S420F', 'NE-EH227', 'NE-TH227', 'NE-BS656', 'NE-BS808', 'NE-BS1500', 'MRO-N550', 'MRO-CV200', 'MRO-GV300', 'MRO-JV300', 'MRO-CS8', 'MRO-RY3000', 'MRO-SBK1', 'MRO-SF6', 'MRO-SV3000', 'ER-M6E', 'ER-F3', 'ER-GE54', 'ER-H3', 'ER-J3', 'ER-J3A', 'ER-K3', 'ER-YJ3', 'ER-YJ3A', 'ER-YK3', 'ER-H10', 'ER-SD100', 'ER-JD310', 'ER-JD310A', 'ER-JD410', 'ER-JD410A', 'ER-JD510', 'ER-JD510A', 'ER-KD320', 'ER-KD420', 'ER-KD520', 'ER-LD330', 'ER-LD430', 'ER-LD530', 'ER-WD3000', 'AX-GX2', 'AX-PX1', 'AX-PX2', 'NE-EH2', 'NE-EH22', 'NE-EZ2', 'NE-S200F', 'NE-EH212', 'NE-EH228', 'NE-TH224', 'NE-TH228', 'NE-BS658', 'NE-BS6A', 'NE-BS655', 'NE-BS9C', 'NE-JBS652', 'NE-JBS653', 'NE-JBS654', 'NE-SBS656', 'NE-UBS10C')
and not exists (
  select 1 from appliance_parts ap where ap.appliance_id = a.id and ap.part_id = p.id
);
