-- Auto-generated by scripts/enrich-parts.ts
-- 2026-05-18T06:37:33.342Z

update parts set image_url = 'https://thumbnail.image.rakuten.co.jp/@0_mall/avac/cabinet/img155/1.jpg?_ex=128x128' where id = 'b882fc17-50df-45e4-9c78-8ae69bd17d62';
