/**
 * 既存 parts のうち image_url / manufacturer_part_number が null のものに
 * 楽天 API を叩いて補完するスクリプト。
 *
 * 戦略:
 *   - parts テーブルから image_url is null の行を全件読む
 *   - 各行の name をキーワードに楽天検索
 *   - top hit の mediumImageUrl と、itemName から抽出した品番を取得
 *   - 結果を seed-enrichment.sql に UPDATE 文として書き出し
 *
 * 使い方:
 *   pnpm tsx scripts/enrich-parts.ts
 *
 * 出力:
 *   supabase/seed-enrichment.sql に UPDATE 文を append。
 *   stderr に進行ログ。
 *
 * 注意:
 *   - rate limit 1 req/sec、3000 件なら 60-70 分
 *   - 既に image_url を持つ parts は触らない（冪等性確保）
 */

import { createClient } from "@supabase/supabase-js";
import { config } from "dotenv";
import { appendFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

config({ path: resolve(process.cwd(), ".env.local"), quiet: true });

const OUTPUT = "supabase/seed-enrichment.sql";

// メーカー別の典型的な部品番号パターン
const PART_NUMBER_PATTERNS: RegExp[] = [
  /\bARE[0-9]{1,3}-[A-Z][0-9]+\b/g,
  /\bARB[0-9]+-[A-Z0-9]+\b/g,
  /\bAXW[0-9]+-?[A-Z0-9]+\b/g,
  /\bAVE[0-9]+-[0-9A-Z]+\b/g,
  /\bA[0-9]{3}-[0-9]{3,4}\b/g,
  /\bB[0-9]{3}-[0-9][A-Z]\b/g,
  /\bJPI[0-9]{3,4}\b/g,
  /\bJPL[0-9]{3,4}\b/g,
  /\bJPC[0-9]{3,4}\b/g,
  /\bRC-[0-9]+[A-Z]+\b/g,
  /\bNJ-[A-Z]{2,4}[0-9]+\b/g,
  /\bM[0-9]{2}[A-Z][0-9]{4,6}\b/g,
  /\b[0-9]{3}[A-Z][0-9]{4}\b/g, // 東芝系 (320A2450)
  /\b[0-9]{8,12}\b/g, // シャープ・東芝冷蔵庫系
];

interface Part {
  id: string;
  name: string;
  manufacturer_part_number: string | null;
}

interface RawItem {
  itemName?: string;
  mediumImageUrls?: Array<{ imageUrl: string } | string>;
}

async function searchRakuten(keyword: string): Promise<RawItem[]> {
  const appId = process.env.RAKUTEN_APP_ID!;
  const accessKey = process.env.RAKUTEN_ACCESS_KEY!;
  const origin = process.env.RAKUTEN_ORIGIN ?? "http://example.com";

  const params = new URLSearchParams({
    applicationId: appId,
    keyword,
    hits: "5",
    formatVersion: "2",
    availability: "1",
  });
  const url = `https://openapi.rakuten.co.jp/ichibams/api/IchibaItem/Search/20260401?${params}`;
  const res = await fetch(url, {
    headers: { accessKey, Origin: origin, Referer: `${origin}/` },
  });
  if (!res.ok) return [];
  const json = (await res.json()) as { Items?: RawItem[] };
  return json.Items ?? [];
}

function extractPartNumber(items: RawItem[], excludeModel: string): string | null {
  for (const item of items) {
    const name = item.itemName ?? "";
    for (const pattern of PART_NUMBER_PATTERNS) {
      pattern.lastIndex = 0;
      let m: RegExpExecArray | null = pattern.exec(name);
      while (m) {
        const pn = m[0];
        if (pn !== excludeModel && pn.length >= 5) return pn;
        m = pattern.exec(name);
      }
    }
  }
  return null;
}

function extractImage(items: RawItem[]): string | null {
  for (const item of items) {
    const first = item.mediumImageUrls?.[0];
    if (!first) continue;
    return typeof first === "string" ? first : first.imageUrl;
  }
  return null;
}

function sqlEscape(s: string): string {
  return s.replace(/'/g, "''");
}

async function main() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL!;
  const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
  const supabase = createClient(url, key);

  // 補完対象: image_url is null の parts
  const { data, error } = await supabase
    .from("parts")
    .select("id, name, manufacturer_part_number")
    .is("image_url", null)
    .order("name");
  if (error) throw error;
  const parts = (data ?? []) as Part[];

  console.error(`Found ${parts.length} parts to enrich.`);

  // ファイル初期化
  writeFileSync(
    OUTPUT,
    `-- Auto-generated by scripts/enrich-parts.ts\n-- ${new Date().toISOString()}\n\n`,
  );

  let updated = 0;
  let skipped = 0;

  for (let i = 0; i < parts.length; i++) {
    const part = parts[i];
    // 部品名の最後の単語 = 機種型番。それで除外用 model_number を作る
    const tokens = part.name.split(/\s+/);
    const excludeModel = tokens[tokens.length - 1];

    try {
      const items = await searchRakuten(part.name);
      const image = extractImage(items);
      const partNumber = part.manufacturer_part_number ?? extractPartNumber(items, excludeModel);

      if (image || partNumber) {
        const sets: string[] = [];
        if (image) sets.push(`image_url = '${sqlEscape(image)}'`);
        if (partNumber && !part.manufacturer_part_number) {
          sets.push(`manufacturer_part_number = '${sqlEscape(partNumber)}'`);
        }
        if (sets.length > 0) {
          appendFileSync(OUTPUT, `update parts set ${sets.join(", ")} where id = '${part.id}';\n`);
          updated++;
        }
      } else {
        skipped++;
      }

      if ((i + 1) % 50 === 0) {
        console.error(`[${i + 1}/${parts.length}] updated=${updated} skipped=${skipped}`);
      }
    } catch (e) {
      console.error(`  error on ${part.name}: ${e instanceof Error ? e.message : e}`);
    }
    await new Promise((r) => setTimeout(r, 1300));
  }

  console.error(`\nDone. Total ${updated} parts have updates written.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
