/**
 * 楽天の itemName に部品キーワードが含まれるかで verified 判定するスクリプト。
 * is_verified = false の機種を全件走査し、楽天で型番検索 → 結果に部品系の語が
 * 含まれていれば「楽天で部品単体販売の実績あり」として verified に格上げする UPDATE 文を出力。
 *
 * 使い方:
 *   pnpm tsx scripts/verify-appliances.ts
 *
 * 出力:
 *   supabase/seed-verify.sql に UPDATE 文を書き出す。
 *   stderr に進行ログ。
 *
 * 想定実行時間:
 *   2,500+ クエリ × 1.3 秒 = 約 55 分
 */

import { createClient } from "@supabase/supabase-js";
import { config } from "dotenv";
import { appendFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

config({ path: resolve(process.cwd(), ".env.local"), quiet: true });

const OUTPUT = "supabase/seed-verify.sql";

// 部品単体販売の証拠となるキーワード
const PART_KEYWORDS = [
  "内釜",
  "内なべ",
  "内鍋",
  "うちなべ",
  "うち釜",
  "フィルター",
  "ふぃるたー",
  "パッキン",
  "ホース",
  "バッテリー",
  "ばってりー",
  "蓄電池",
  "充電池",
  "替え電池",
  "紙パック",
  "集塵パック",
  "ダストパック",
  "リモコン",
  "蒸気ふた",
  "蒸気カバー",
  "蒸気弁",
  "蒸気キャップ",
  "ターンテーブル",
  "回転皿",
  "角皿",
  "製氷皿",
  "アイストレイ",
  "床ブラシ",
  "床用ブラシ",
  "クリーナーヘッド",
  "適合",
  "対応機種",
  "純正部品",
  "交換用",
  "互換品",
];

interface Appliance {
  id: string;
  manufacturer: string;
  model_number: string;
}

interface RakutenItem {
  itemName?: string;
}

async function searchRakuten(keyword: string): Promise<RakutenItem[]> {
  const appId = process.env.RAKUTEN_APP_ID!;
  const accessKey = process.env.RAKUTEN_ACCESS_KEY!;
  const origin = process.env.RAKUTEN_ORIGIN ?? "http://example.com";

  const params = new URLSearchParams({
    applicationId: appId,
    keyword,
    hits: "10",
    formatVersion: "2",
    availability: "1",
  });
  const url = `https://openapi.rakuten.co.jp/ichibams/api/IchibaItem/Search/20260401?${params}`;
  const res = await fetch(url, {
    headers: { accessKey, Origin: origin, Referer: `${origin}/` },
  });
  if (!res.ok) return [];
  const json = (await res.json()) as { Items?: RakutenItem[] };
  return json.Items ?? [];
}

function hasPartEvidence(items: RakutenItem[]): boolean {
  for (const it of items) {
    const name = it.itemName ?? "";
    for (const kw of PART_KEYWORDS) {
      if (name.includes(kw)) return true;
    }
  }
  return false;
}

function sqlEscape(s: string): string {
  return s.replace(/'/g, "''");
}

async function main() {
  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  );

  // ページネーション
  const appliances: Appliance[] = [];
  const pageSize = 1000;
  for (let offset = 0; ; offset += pageSize) {
    const { data, error } = await supabase
      .from("appliances")
      .select("id, manufacturer, model_number")
      .eq("is_verified", false)
      .order("model_number")
      .range(offset, offset + pageSize - 1);
    if (error) throw error;
    const rows = (data ?? []) as Appliance[];
    appliances.push(...rows);
    if (rows.length < pageSize) break;
  }
  console.error(`Verifying ${appliances.length} unverified appliances`);

  writeFileSync(
    OUTPUT,
    `-- Auto-generated by scripts/verify-appliances.ts\n-- ${new Date().toISOString()}\n-- Re-classifies unverified -> verified when 楽天 search reveals part listings\n\n`,
  );

  let verified = 0;
  let skipped = 0;

  for (let i = 0; i < appliances.length; i++) {
    const a = appliances[i];
    try {
      const items = await searchRakuten(a.model_number);
      if (hasPartEvidence(items)) {
        appendFileSync(
          OUTPUT,
          `update appliances set is_verified = true where model_number = '${sqlEscape(a.model_number)}' and manufacturer = '${sqlEscape(a.manufacturer)}';\n`,
        );
        verified++;
      } else {
        skipped++;
      }

      if ((i + 1) % 50 === 0) {
        console.error(
          `[${i + 1}/${appliances.length}] verified=${verified} skipped=${skipped}`,
        );
      }
    } catch (e) {
      console.error(`  error on ${a.model_number}: ${e instanceof Error ? e.message : e}`);
    }
    await new Promise((r) => setTimeout(r, 1300));
  }

  console.error(`\nDone. ${verified} appliances will graduate to verified.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
