-- ============================================================
-- 空気清浄機の初期 seed
-- discover-air-purifiers.ts（楽天のフィルター商品タイトルからモデル抽出）由来。
-- フィルター商品名に登場した実在モデルのみ。部品関連キーワードを含む楽天タイトルに
-- 出現したため is_verified = true（プロジェクトの検証基準に準拠）。
-- 冪等性のため on conflict do nothing。
-- ============================================================

insert into appliances (manufacturer, category, model_number, is_verified) values
  -- シャープ KC シリーズ（加湿空気清浄機）
  ('シャープ', 'air_purifier', 'KC-R50', true),
  ('シャープ', 'air_purifier', 'KC-P50', true),
  ('シャープ', 'air_purifier', 'KC-N50', true),
  ('シャープ', 'air_purifier', 'KC-L50', true),
  ('シャープ', 'air_purifier', 'KC-J50', true),
  ('シャープ', 'air_purifier', 'KC-H50', true),
  ('シャープ', 'air_purifier', 'KC-G50', true),
  ('シャープ', 'air_purifier', 'KC-F50', true),
  ('シャープ', 'air_purifier', 'KC-E50', true),
  ('シャープ', 'air_purifier', 'KC-D50', true),
  ('シャープ', 'air_purifier', 'KC-B50', true),
  ('シャープ', 'air_purifier', 'KC-A50', true),
  ('シャープ', 'air_purifier', 'KC-G40', true),
  ('シャープ', 'air_purifier', 'KC-F40', true),
  ('シャープ', 'air_purifier', 'KC-E40', true),
  ('シャープ', 'air_purifier', 'KC-D40', true),
  ('シャープ', 'air_purifier', 'KC-B40', true),
  ('シャープ', 'air_purifier', 'KC-F70', true),
  ('シャープ', 'air_purifier', 'KC-E70', true),
  ('シャープ', 'air_purifier', 'KC-D70', true),
  ('シャープ', 'air_purifier', 'KC-B70', true),
  ('シャープ', 'air_purifier', 'KC-A70', true),
  -- シャープ KI シリーズ（高級加湿空気清浄機）
  ('シャープ', 'air_purifier', 'KI-LS50', true),
  ('シャープ', 'air_purifier', 'KI-JS50', true),
  ('シャープ', 'air_purifier', 'KI-HS50', true),
  ('シャープ', 'air_purifier', 'KI-GS50', true),
  ('シャープ', 'air_purifier', 'KI-DX50', true),
  ('シャープ', 'air_purifier', 'KI-BX50', true),
  ('シャープ', 'air_purifier', 'KI-JS70', true),
  ('シャープ', 'air_purifier', 'KI-HS70', true),
  ('シャープ', 'air_purifier', 'KI-GS70', true),
  ('シャープ', 'air_purifier', 'KI-FX75', true),
  ('シャープ', 'air_purifier', 'KI-EX75', true),
  -- Panasonic F-VC / F-VX シリーズ（加湿空気清浄機）
  ('Panasonic', 'air_purifier', 'F-VC70XS', true),
  ('Panasonic', 'air_purifier', 'F-VC70XR', true),
  ('Panasonic', 'air_purifier', 'F-VC70XP', true),
  ('Panasonic', 'air_purifier', 'F-VC70XM', true),
  ('Panasonic', 'air_purifier', 'F-VC70XL', true),
  ('Panasonic', 'air_purifier', 'F-VXS70', true),
  ('Panasonic', 'air_purifier', 'F-VXR70', true),
  ('Panasonic', 'air_purifier', 'F-VXP70', true),
  ('Panasonic', 'air_purifier', 'F-VXM70', true),
  ('Panasonic', 'air_purifier', 'F-VXL70', true),
  ('Panasonic', 'air_purifier', 'F-VXS90', true),
  ('Panasonic', 'air_purifier', 'F-VXR90', true),
  ('Panasonic', 'air_purifier', 'F-VXP90', true),
  ('Panasonic', 'air_purifier', 'F-VXM90', true),
  ('Panasonic', 'air_purifier', 'F-VXL90', true),
  ('Panasonic', 'air_purifier', 'F-VXS55', true),
  ('Panasonic', 'air_purifier', 'F-VXR55', true),
  ('Panasonic', 'air_purifier', 'F-VC55XS', true),
  ('Panasonic', 'air_purifier', 'F-VXH50', true),
  ('Panasonic', 'air_purifier', 'F-VXG50', true),
  ('Panasonic', 'air_purifier', 'F-VXF65', true),
  -- ダイキン MCK / ACK / TCK シリーズ
  ('ダイキン', 'air_purifier', 'MCK70W', true),
  ('ダイキン', 'air_purifier', 'MCK70V', true),
  ('ダイキン', 'air_purifier', 'MCK70U', true),
  ('ダイキン', 'air_purifier', 'MCK70R', true),
  ('ダイキン', 'air_purifier', 'MCK70P', true),
  ('ダイキン', 'air_purifier', 'MCK70N', true),
  ('ダイキン', 'air_purifier', 'MCK70M', true),
  ('ダイキン', 'air_purifier', 'MCK55R', true),
  ('ダイキン', 'air_purifier', 'MCK55P', true),
  ('ダイキン', 'air_purifier', 'MCK55N', true),
  ('ダイキン', 'air_purifier', 'ACK70W', true),
  ('ダイキン', 'air_purifier', 'ACK70V', true),
  ('ダイキン', 'air_purifier', 'ACK70U', true),
  ('ダイキン', 'air_purifier', 'ACK70R', true),
  ('ダイキン', 'air_purifier', 'ACK70P', true),
  ('ダイキン', 'air_purifier', 'ACK70N', true),
  ('ダイキン', 'air_purifier', 'ACK70M', true),
  ('ダイキン', 'air_purifier', 'TCK70R', true),
  ('ダイキン', 'air_purifier', 'TCK70P', true),
  ('ダイキン', 'air_purifier', 'TCK55R', true),
  ('ダイキン', 'air_purifier', 'TCK55P', true),
  -- 日立 EP（クリエア）シリーズ
  ('日立', 'air_purifier', 'EP-NVG110', true),
  ('日立', 'air_purifier', 'EP-NVG90', true),
  ('日立', 'air_purifier', 'EP-NVG70', true),
  ('日立', 'air_purifier', 'EP-MVG110', true),
  ('日立', 'air_purifier', 'EP-MVG90', true),
  ('日立', 'air_purifier', 'EP-MVG70', true),
  ('日立', 'air_purifier', 'EP-LVG110', true),
  -- バルミューダ
  ('バルミューダ', 'air_purifier', 'EJT-1100SD', true),
  ('バルミューダ', 'air_purifier', 'EJT-1000', true),
  -- カドー
  ('カドー', 'air_purifier', 'AP-C320', true),
  ('カドー', 'air_purifier', 'AP-C200', true),
  ('カドー', 'air_purifier', 'AP-C120', true),
  ('カドー', 'air_purifier', 'AP-C110', true),
  ('カドー', 'air_purifier', 'AP-C100', true)
on conflict (manufacturer, model_number) do nothing;
